### ISSUE TITLE
关于promethues agent模式如何使用

### ISSUE THREAD

**Issue by ysj2018** [flashcatcloud/categraf#1031]
### Relevant config.toml

```toml
我使用categraf  v0.3.73
我对于使用promethues agent 模式不太清楚
我看到配置文件中有
[prometheus]
enable = false
scrape_config_file = "/path/to/in_cluster_scrape.yaml"
## log level, debug warn info error
log_level = "info"
## wal file storage path ,default ./data-agent
# wal_storage_path = "/path/to/storage"
## wal reserve time duration, default value is 2 hour
# wal_min_duration = 2
这样一段，
我理解如果我要采集linux指标，我需要安装一个node_exportor暴漏metric接口
这里scrape_config_file是指向我prometheus的配置文件（用来抓取node—export暴漏的数据）

但是我看到input.promethues里也有一个配置文件，我有点搞不太清楚两者的关系
```

### Logs from categraf

```text
还未开始使用
```

### System info

categraf 0.3.73  ， Linux tvvmdc0065 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

### Steps to reproduce

我是部署了node_exoprtor
然后config.tomlpei配置了开启promethues，并且scrape_config_file 参数指向了我原来promethues的配置文件

但是我不明白input.promethues里的配置文件应该怎样配

### Expected behavior

请跟我说一下，使用promethues agent的大致步骤，我上面的理解对吗？ input里我应该怎样配，开启的话，是要指定input的promethues开启吗

### Actual behavior

实际未成功探测
