### ISSUE TITLE
日志采集时，能否针对不同的日志使用不同的处理规则

### ISSUE THREAD

**Issue by dbadylan** [flashcatcloud/categraf#1042]
能否配置多个 items，每个 item 指定不同的 log_processing_rules？单个 item 和 rule 如何实现关联？

**Comment by kongfei605** [comment]
可以的 https://flashcat.cloud/docs/content/flashcat-monitor/categraf/4-logs-agent/

**Comment by dbadylan** [comment]
> 可以的 https://flashcat.cloud/docs/content/flashcat-monitor/categraf/4-logs-agent/

![Dingtalk_20240901111033](https://github.com/user-attachments/assets/032cc5ca-b49b-41e7-8a24-66f3fe70ea37)

这部分没看明白，各item怎么和不同rule形成对应关系的，靠缩进吗，但toml对缩进是不敏感的吧？

**Comment by kongfei605** [comment]
toml是靠前缀，rules跟着items 就对了。

**Comment by dbadylan** [comment]
配置A：

```toml
[[logs.items]]
path="/path/to/f1.log"

[[logs.items.log_processing_rules]]
pattern="pattern1"

[[logs.items]]
path="/path/to/f2.log"

[[logs.items.log_processing_rules]]
pattern="pattern2"
```

配置B：

```toml
[[logs.items]]
path="/path/to/f1.log"

[[logs.items]]
path="/path/to/f2.log"

[[logs.items.log_processing_rules]]
pattern="pattern1"

[[logs.items.log_processing_rules]]
pattern="pattern2"
```

上述2段都是合法的toml格式，但配置B明显不符合预期，很容易出错，也会有误解。
