### ISSUE TITLE
使用categraf的oracle模块配合夜莺提供的仪表盘有些页面是空白的如何处理？

### ISSUE THREAD

**Issue by eguotangseng** [flashcatcloud/categraf#1048]
### Relevant config.toml

```toml
[[metrics]]
mesurement = "sessions"
label_fields = [ "status", "type" ]
metric_fields = [ "value" ]
timeout = "3s"
request = '''
SELECT status, type, COUNT(*) as value FROM v$session GROUP BY status, type
'''
有仪表盘中oracle_sysmetric_buffer_cache_hit_ratio_value，这个页面的sql语言吗？
```

### Logs from categraf

```text
页面没有对应的sql语句，不知道如何编写
```

### System info

oracle

### Steps to reproduce

1.想问问大家如何编写sql出数来支持仪表盘的显示
2.
3.
...

### Expected behavior

就是仪表盘

### Actual behavior

就是仪表盘

### Additional info

就是仪表盘
