### ISSUE TITLE
nvidia_smi 插件报错

### ISSUE THREAD

**Issue by Derek-zd** [flashcatcloud/categraf#1056]
### Relevant config.toml

```toml
# interval = 15

# exec local command
# e.g. nvidia_smi_command = "nvidia-smi"
nvidia_smi_command = "nvidia-smi"

# exec remote command
# nvidia_smi_command = "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null SSH_USER@SSH_HOST nvidia-smi"

# Comma-separated list of the query fields.
# You can find out possible fields by running `nvidia-smi --help-query-gpus`.
# The value `AUTO` will automatically detect the fields to query.
query_field_names = "AUTO"

# query_timeout is used to set the query timeout to avoid the delay of date collection.
query_timeout = "5s"
```

### Logs from categraf

```text
Sep 19 16:23:52 zj-4090-59 categraf[79833]: 2024/09/19 16:23:52 metrics_agent.go:276: E! failed to init input: local.nvidia_smi error: unexpected query field: vgpu_driver_capability.heterogenous_multivGPU
```

### System info

Ubuntu 22.04

### Steps to reproduce

1.开启 nvidia_smi 插件
2. 正常有监控数据
3. 显卡出问题了，掉卡了，通常表现为 nvidia_smi 命令卡住出不来，或命令报错 nable to determine the device handle for GPU0000:CF:00.0: Unknown Errornon-zero return code 。使用 nvidia_smi -L 命令可以看到正常的卡和错误的卡。
![20240919-181818](https://github.com/user-attachments/assets/b9b2b3c1-4b10-4767-8268-4e7b8afc457b)

4. categraf 会不再上报 显卡监控数据，导致 告警失效。
...

### Expected behavior

有显卡掉卡时监控数据，其他正常的卡的监控数据可以继续正常上报，

### Actual behavior

不再上报显卡相关的监控数据
