### ISSUE TITLE
categraf采集器ping的结果,会出现隔5分钟查询的时候同时出现2条记录,导致等于1的告警,而此时ping是通的,不应该告警才是.

### ISSUE THREAD

**Issue by shier-1212** [flashcatcloud/categraf#1061]
### Relevant config.toml

```toml
[[instances]]
concurrency = 15
timeout = 5.0
# interval_times = 20

targets = [ "xxx.xxx.xxx.xxx", "10.88.200.2", "xxx.xxx.xxx.xxx"]

[instances.labels]
level = "p1"
```

### Logs from categraf

```text
xxx
```

### System info

centos7.4 内核版本 4.18

### Docker

xxx

### Steps to reproduce

1.
2.
3.
...

### Expected behavior

xxx

### Actual behavior

xxx

### Additional info

![image](https://github.com/user-attachments/assets/173cc748-eae1-4595-8c7d-1948f03851b1)
