### ISSUE TITLE
input.exec 设置间隔时间长不执行任务的问题

### ISSUE THREAD

**Issue by rayn316** [flashcatcloud/categraf#1075]
### Relevant config.toml

```toml
cat input.exec/default.toml
# collect interval
interval = 10

# 获取目录大小
[[instances]]
commands = [
"/usr/bin/bash /usr/local/blockpi/node_disk_use.sh"
]
timeout = 60
interval_times = 120
data_format = "prometheus"
```

### Logs from categraf

```text
没有执行日志
```

### System info

v0.3.81-a87cb4ea40fba4a0e4dff9fcfc8b38526c276a80

### Steps to reproduce

1. 手动执行任务脚本确认执行正常 /usr/bin/bash /usr/local/blockpi/node_disk_use.sh
2. 设置好exec配置后重启categraf程序
3. 查询任务执行情况，一直没有执行
...

### Expected behavior

每隔20分钟执行一次任务

### Actual behavior

一直不执行此任务
