### ISSUE TITLE
catgraf input.cloudwatch multiple namespaces not taking effect.

### ISSUE THREAD

**Issue by charles-liming** [flashcatcloud/categraf#1110]
### Relevant config.toml

```toml
#cat cloud.toml |egrep -v "^[ ]+#|^$"
[[instances]]
  region = "ap-southeast-1"
  endpoint_url = "https://monitoring.ap-southeast-1.amazonaws.com"
  period = "5m"
  delay = "5m"
  interval = "5m"
  namespaces = ["AWS/RDS","AWS/ElastiCache"]
  [[instances.metrics]]
    names= ["CPUUtilization","DatabaseConnections","FreeableMemory","FreeStorageSpace","SwapUsage","DBLoadNonCPU","DBLoadCPU","DBLoad","DatabaseMemoryUsagePercentage"] 
     [[instances.metrics.dimensions]]
       name = "DBInstanceIdentifier"
       value = "*"
```

### Logs from categraf

```text
没有error 日志，但是呢，我看了这个插件配置基本跟telegraf插件一致。然后telegraf 配置会出现同样的问题，多个namespace 的时候，后边的namespace  不生效。
```

### System info

categraf-v0.3.32-linux-amd64

### Steps to reproduce

无

### Expected behavior

期望的行为：配置多个namespaces后，下边的配置可以按照namespace  进行筛选各自的监控项，或者查询条件。

### Actual behavior

目前：配置多个namespaces后，看是多个namespace 的时候，只有第一个生效
