### ISSUE TITLE
Categraf使用rocketmq_offset报错。

### ISSUE THREAD

**Issue by zhumengdetianshi** [flashcatcloud/categraf#1159]
### Relevant config.toml

```toml
使用的是docker环境，最新的。
categraf           | 2025/03/11 17:34:22 metrics_agent.go:262: E! failed to load configuration of plugin: local.rocketmq_offset error: toml: line 7 (last key "instances.rocketmq_console_ip_port"): Invalid float value: "172.16.16.3

配置如下
配置1：
# # collect interval
interval = 1

[[instances]]
rocketmq_console_ip_port = 172.16.16.3:15672
ignored_topics = []
# 启用认证, 没有认证的不用配置
username = "admin"
password = "xxxxx"

配置2：
# # collect interval
interval = 1

[[instances]]
rocketmq_console_ip_port = 172.16.16.3:15672
ignored_topics = []
# 启用认证, 没有认证的不用配置
username = "admin"
password = "xxxxx"

谢谢
```

### Logs from categraf

```text
categraf           | 2025/03/11 17:34:22 metrics_agent.go:262: E! failed to load configuration of plugin: local.rocketmq_offset error: toml: line 7 (last key "instances.rocketmq_console_ip_port"): Invalid float value: "172.16.16.3"
```

### System info

docker version Client: Docker Engine - Community  Version:           26.1.3  API version:       1.45  Go version:        go1.21.10  Git commit:        b72abbb  Built:             Thu May 16 08:34:39 2024  OS/Arch:           linux/amd64  Context:           default  Server: Docker Engine - Community  Engine:   Version:          26.1.3   API version:      1.45 (minimum version 1.24)   Go version:       go1.21.10   Git commit:       8e96db1   Built:            Thu May 16 08:33:34 2024   OS/Arch:          linux/amd64   Experimental:     false  containerd:   Version:          1.6.32   GitCommit:        8b3b7ca2e5ce38e8f31a34f35b2b68ceb8470d89  runc:   Version:          1.1.12   GitCommit:        v1.1.12-0-g51d5e94  docker-init:   Version:          0.19.0   GitCommit:        de40ad0

### Docker

docker-compose: 
n9e-v8.0.0-beta.7-linux-amd64/docker/compose-bridge
插件:
https://download.flashcat.cloud/categraf-v0.4.3-linux-amd64.tar.gz
n9e-v8.0.0-beta.7-linux-amd64/docker/compose-bridge/etc-categraf/input.rocketmq_offset

### Steps to reproduce

1.
2.
3.
...

### Expected behavior

采集偏移量

### Actual behavior

采集偏移量

### Additional info

采集偏移量
