### ISSUE TITLE
Categraf v0.4.6 如何暴露Prometheus格式指标

### ISSUE THREAD

**Issue by timeNeverComesBack** [flashcatcloud/categraf#1181]
Categraf v0.4.6 如何暴露Prometheus格式指标？类似于 node_exporter。

对主配置进行了如下配置，但是没有效果。

```toml
[http]
enable = true
address = "0.0.0.0"
port = 9958
use_tls = false
print_access = false
run_mode = "release"
ignore_hostname = false
agent_host_tag = ""
ignore_global_labels = false
```

**Comment by timeNeverComesBack** [comment]
改成如下配置，访问 404。

```toml
[http]
enable = true
address = ":9958"
use_tls = false
print_access = false
run_mode = "release"
ignore_hostname = false
agent_host_tag = ""
ignore_global_labels = false
```
