### ISSUE TITLE
kubernetes 插件执行时错误

### ISSUE THREAD

**Issue by 9k001** [flashcatcloud/categraf#1182]
### Relevant config.toml

```toml
[[instances]]
# # append some labels for series
# labels = { region="cloud", product="n9e" }

# # interval = global.interval * interval_times
# interval_times = 1

# URL for the kubelet
# url = "https://$HOSTIP:10250"
url = "http://localhost:10250"

gather_system_container_metrics = true
gather_node_metrics = true
gather_pod_container_metrics = true
gather_pod_volume_metrics = true
gather_pod_network_metrics = true

## Use bearer token for authorization. ('bearer_token' takes priority)
## If both of these are empty, we'll use the default serviceaccount:
## at: /var/run/secrets/kubernetes.io/serviceaccount/token
# bearer_token = '/data/config/categraf/token'
## OR
bearer_token_string = 'xxxxxx'

## Pod labels to be added as tags.  An empty array for both include and
## exclude will include all labels.
# label_include = []
# label_exclude = ["*"]

## Set response_timeout (default 5 seconds)
# response_timeout = "5s"

## Optional TLS Config
use_tls = true
# tls_ca = "/etc/categraf/ca.pem"
# tls_cert = "/etc/categraf/cert.pem"
# tls_key = "/etc/categraf/key.pem"
## Use TLS but skip chain & host verification
insecure_skip_verify = true
```

### Logs from categraf

```text
2025/04/14 16:28:50 kubernetes.go:113: E! failed to load http://localhost:10250/stats/summary error: http://localhost:10250/stats/summary returned HTTP status 400 Bad Request
```

### System info

categraf v0.4.3-d5d416794195bba5a6f32cb64ba35fa39ec5d9c8

### Steps to reproduce

1.  执行 ./categraf --test --inputs kubernetes
2.
3.
...

### Expected behavior

采集相关数据

### Actual behavior

2025/04/14 16:28:50 kubernetes.go:113: E! failed to load http://localhost:10250/stats/summary error: http://localhost:10250/stats/summary returned HTTP status 400 Bad Request

### Additional info

不管我将token路径写入 toml 文件
or 
将string 写入 toml 均 出现400错误
```
2025/04/14 16:33:44 kubernetes.go:113: E! failed to load http://localhost:10250/stats/summary error: http://localhost:10250/stats/summary returned HTTP status 400 Bad Request
```
但是 我自己使用同样的 token 进行 curl 则可以有很多返回值
```
curl -s -k -H "Authorization: Bearer $token" https://localhost:10250/stats/summary
````

**Comment by kongfei605** [comment]
这个插件过时了， 换cadvisor插件 ， kube-state-metrics采集

<img width="913" alt="Image" src="https://github.com/user-attachments/assets/958e6f01-816b-49f6-a11a-d957995ce36d" />

**Comment by 9k001** [comment]
> 这个插件过时了， 换cadvisor插件 ， kube-state-metrics采集
> 
> <img alt="Image" width="913" src="https://private-user-images.githubusercontent.com/12164762/433292267-958e6f01-816b-49f6-a11a-d957995ce36d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDQ2MjQ0MzQsIm5iZiI6MTc0NDYyNDEzNCwicGF0aCI6Ii8xMjE2NDc2Mi80MzMyOTIyNjctOTU4ZTZmMDEtODE2Yi00OWY2LWExMWEtZDk1Nzk5NWNlMzZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA0MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNDE0VDA5NDg1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhNjNmMDFjNjZlNDE1ZTM2ZmJjZWMzYmUwYjU1NDJkYzM3NmYzMzVkYzc5MmRiOGIzOTg0MmI5NDdhNWFhYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KHVS53c9ZJYjFBlVDOujGrxavMiqr8f5QUT2fzxLYfQ">

明白了，测试测试。
我想了解一下，这个是采集kubelet 的数据，那也就意味着 master 节点和 node节点均需要部署咯？
当然这个肯定可以通过ds进行部署，但是我还是希望通过二进制，和k8s集群解耦部署。

**Comment by 9k001** [comment]
> 这个插件过时了， 换cadvisor插件 ， kube-state-metrics采集
> 
> <img alt="Image" width="913" src="https://private-user-images.githubusercontent.com/12164762/433292267-958e6f01-816b-49f6-a11a-d957995ce36d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDQ2MjY0MTgsIm5iZiI6MTc0NDYyNjExOCwicGF0aCI6Ii8xMjE2NDc2Mi80MzMyOTIyNjctOTU4ZTZmMDEtODE2Yi00OWY2LWExMWEtZDk1Nzk5NWNlMzZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA0MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNDE0VDEwMjE1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwN2RjM2NlYTc1YjUwNTZlZDg1M2ViOTNmNjJkN2FjZDFjMWRiMDhlZjA1YTNhODc0YjA5NWQxZmUxNTRlZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CeSvb9QYE1LnRAl9dqv5rowSg1GXPUOiL0IudtLZfs0">

```
instances.go:227: E! failed to query url: https://127.0.0.1:10250/metrics/cadvisor error: Get "https://127.0.0.1:10250/metrics/cadvisor": tls: failed to verify certificate: x509: cannot validate certificate for 127.0.0.1 because it doesn't contain any IP SANs
```
设置跳过ssl验证之后还是出现这个x509....

**Comment by kongfei605** [comment]
> > 这个插件过时了， 换cadvisor插件 ， kube-state-metrics采集
> > <img alt="Image" width="913" src="https://private-user-images.githubusercontent.com/12164762/433292267-958e6f01-816b-49f6-a11a-d957995ce36d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDQ2MjQ0MzQsIm5iZiI6MTc0NDYyNDEzNCwicGF0aCI6Ii8xMjE2NDc2Mi80MzMyOTIyNjctOTU4ZTZmMDEtODE2Yi00OWY2LWExMWEtZDk1Nzk5NWNlMzZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA0MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNDE0VDA5NDg1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhNjNmMDFjNjZlNDE1ZTM2ZmJjZWMzYmUwYjU1NDJkYzM3NmYzMzVkYzc5MmRiOGIzOTg0MmI5NDdhNWFhYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KHVS53c9ZJYjFBlVDOujGrxavMiqr8f5QUT2fzxLYfQ">
> 
> 明白了，测试测试。 我想了解一下，这个是采集kubelet 的数据，那也就意味着 master 节点和 node节点均需要部署咯？ 当然这个肯定可以通过ds进行部署，但是我还是希望通过二进制，和k8s集群解耦部署。

对 ，采集kubelet端口，但是这个插件新版本K8s中可能没有这个接口了，老版本K8s中也是信息比较少。用二进制部署会有很多额外的工作，比如token自动更新。用daemonset更方便。

**Comment by kongfei605** [comment]
可以列一些面板需要调整的地方，我们一块来看看。 文档、或者面板、规则有问题的地方都可以提，越详细越好。

**Comment by 9k001** [comment]
> 可以列一些面板需要调整的地方，我们一块来看看。 文档、或者面板、规则有问题的地方都可以提，越详细越好。

我举几个例子。
我根据官方博客 [Kubernetes监控手册10-使用 kube-state-metrics 监控 Kubernetes 对象](https://flashcat.cloud/blog/kubernetes-monitoring-10-kube-state-metrics/)
使用 kube-state-metrics ，采集某个K8S集群的数据， 其中谈到 **prometheus agent mode** 抓取，代码如下
```
- job_name: 'kube-state-metrics'
  kubernetes_sd_configs:
  - role: endpoints
  scheme: http
  relabel_configs:
  - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
    action: keep
    regex: kube-system;kube-state-metrics;http-metrics

- job_name: 'kube-state-metrics-self'
  kubernetes_sd_configs:
  - role: endpoints
  scheme: http
  relabel_configs:
  - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
    action: keep
    regex: kube-system;kube-state-metrics;telemetry
```
其用到的[dashboard](https://github.com/flashcatcloud/categraf/blob/main/inputs/kube_state_metrics/dashboard.json)
能明显看到 

```
{
    "name": "Kube state",
    "tags": "kube-state-metrics",
    "configs": {
        "var": [
            {
                "name": "cluster",
                "definition": "label_values(kube_node_info, cluster)",
                "multi": true,
                "allOption": true
            }
        ],
```
使用 采集的数据中含有 **cluster** 的标签，获取到的 集群信息。
这个需要在采集器中加入标签信息，而博客中却没有。

这个问题，其实广泛存在与各个 categraf 原生的 dashboard ,
最明显的问题就是 **ident**. 而全局配置文件conf/config.toml 已经改为了使用 **hostname**。
当然，这个 **ident** 设置是需要有一些技巧的。不同的dashboard 也有自己的**ident**方法。
这方面，我觉得还是要跟使用者讲一下这个问题。
