### ISSUE TITLE
processor_enum 结合 interval 的错误

### ISSUE THREAD

**Issue by robotneo** [flashcatcloud/categraf#1221]
### Relevant config.toml

```toml
interval = "1s"

[[instances]]
interval_times = 1
...

# 枚举值映射
[[instances.processor_enum]]
  metrics = ["*status"]
  [instances.processor_enum.value_mappings]
    "UP" = 1
    "DOWN" = 0
```

### Logs from categraf

```text
metrics_agent.go:262: E! failed to load configuration of plugin: local.gnmi error: toml: incompatible types: TOML key "instances.processor_enum.value_mappings.interval" has type string; destination has type float
```

### System info

Ubuntu 24.04

### Steps to reproduce

1.
2.
3.
...

### Expected behavior

interval = 1

[[instances]]
interval_times = 1
...

# 枚举值映射
[[instances.processor_enum]]
  metrics = ["*status"]
  [instances.processor_enum.value_mappings]
    "UP" = 1
    "DOWN" = 0

这个格式是正常的，也就是带带单位的 interval 不行，纯粹的数字型正常。

### Actual behavior

interval = 1

[[instances]]
interval_times = 1
...

# 枚举值映射
[[instances.processor_enum]]
  metrics = ["*status"]
  [instances.processor_enum.value_mappings]
    "UP" = 1
    "DOWN" = 0

这个格式是正常的，也就是带带单位的 interval 不行，纯粹的数字型正常。
