### ISSUE TITLE
【Bug】关于 SMART 采集中同一块硬盘，两个 Power 标签的问题

### ISSUE THREAD

**Issue by 9k001** [flashcatcloud/categraf#1224]
### Relevant config.toml

```toml
# Read metrics from storage devices supporting S.M.A.R.T.
# # collect interval
interval = 15

[[instances]]
    ## Optionally specify the path to the smartctl executable
    path_smartctl = "/usr/sbin/smartctl"

    ## Optionally specify the path to the nvme-cli executable
    path_nvme = "/usr/sbin/nvme"

    ## Optionally specify if vendor specific attributes should be propagated for NVMe disk case
    ## ["auto-on"] - automatically find and enable additional vendor specific disk info
    ## ["vendor1", "vendor2", ...] - e.g. "Intel" enable additional Intel specific disk info
    #  enable_extensions = ["auto-on"]

    ## On most platforms used cli utilities requires root access.
    ## Setting 'use_sudo' to true will make use of sudo to run smartctl or nvme-cli.
    ## Sudo must be configured to allow the telegraf user to run smartctl or nvme-cli
    ## without a password.
    # use_sudo = true

    ## Skip checking disks in this power mode. Defaults to
    ## "standby" to not wake up disks that have stopped rotating.
    ## See --nocheck in the man pages for smartctl.
    ## smartctl version 5.41 and 5.42 have faulty detection of
    ## power mode and might require changing this value to
    ## "never" depending on your disks.
    # nocheck = "standby"

    ## Gather all returned S.M.A.R.T. attribute metrics and the detailed
    ## information from each drive into the 'smart_attribute' measurement.
    attributes = true

    ## Optionally specify devices to exclude from reporting if disks auto-discovery is performed.
    # excludes = [ "/dev/pass6" ]

    ## Optionally specify devices and device type, if unset
    ## a scan (smartctl --scan and smartctl --scan -d nvme) for S.M.A.R.T. devices will be done
    ## and all found will be included except for the excluded in excludes.
    # devices = [ "/dev/ada0 -d atacam", "/dev/nvme0"]
    # devices = ["dev/nvme0 -d nvme", "/dev/nvme0"]
    devices = ['/dev/sda', '/dev/sdb', '/dev/sdc', '/dev/sdd']
    ## Timeout for the cli command to complete.
    timeout = "30s"

    ## Optionally call smartctl and nvme-cli with a specific concurrency policy.
    ## By default, smartctl and nvme-cli are called in separate threads (goroutines) to gather disk attributes.
    ## Some devices (e.g. disks in RAID arrays) may have access limitations that require sequential reading of
    ## SMART data - one individual array drive at the time. In such case please set this configuration option
    ## to "sequential" to get readings for all drives.
    ## valid options: concurrent, sequential
    # read_method = "concurrent"
```

### Logs from categraf

```text
1748264877 21:07:57 smart_device_temp_c Env=BASIC Model=RD450 OS=Debian Region=xxx Type=virtualMachine Vendor=Lenovo agent_hostname=xxx capacity=2000398934016 device=sda enabled=Enabled ident=xxx model=ST2000NM000B-2TD100 power=ACTIVE serial_no=WRE12WE6 wwn=5000c500fa608486 34
1748264877 21:07:57 smart_device_temp_c Env=BASIC Model=RD450 OS=Debian Region=xxx Type=virtualMachine Vendor=Lenovo agent_hostname=xxx capacity=2000398934016 device=sdb enabled=Enabled ident=xxx model=ST2000NM000B-2TD100 power=IDLE_A serial_no=WRE13433 wwn=5000c500fa60cfa9 34
1748264877 21:07:57 smart_device_temp_c Env=BASIC Model=RD450 OS=Debian Region=xxx Type=virtualMachine Vendor=Lenovo agent_hostname=xxx capacity=2000398934016 device=sdc enabled=Enabled ident=xxx model=ST2000NM0055_________03X3795______LENOVO power=IDLE_A serial_no=ZC21WDNY wwn=5000c500af9ab4f3 31
1748264877 21:07:57 smart_device_temp_c Env=BASIC Model=RD450 OS=Debian Region=xxx Type=virtualMachine Vendor=Lenovo agent_hostname=xxx capacity=2000398934016 device=sdd enabled=Enabled ident=xxx model=ST2000NM0055_________03X3795______LENOVO power=IDLE_A serial_no=ZC21WEGJ wwn=5000c500af9ade54 32
```

### System info

v0.4.3-d5d416794195bba5a6f32cb64ba35fa39ec5d9c8

### Steps to reproduce

执行如下命令
```
./categraf --test --inputs smart |grep smart_device_temp_c
```

### Expected behavior

出现针对 一块硬盘的 在某个时刻的一种状态。

### Actual behavior

![Image](https://github.com/user-attachments/assets/c5a3af41-9b76-4ef7-94f3-189f409ec73a)
可能出现两种状态

### Additional info

我简要描述一下目前的硬件情况.
我有一台服务器, 其中包含4块硬盘 分别是 /dev/sda /dev/sdb /dev/sdc /dev/sdd 
其中 /dev/sda /dev/sdb 为希捷硬盘同一型号   /dev/sdc /dev/sdd  为联想硬盘同一型号
目前问题出在 /dev/sda /dev/sdb 上。
具体问题如下：
关于 /dev/sda 在使用 
```
watch -n 1 "smartctl -n standby -a /dev/sdb | grep -i 'power mode'"
```
查看其power mode 变化的过程中 会出现以下两种状态：
Power mode was:   IDLE_A
Power mode is:    ACTIVE or IDLE
而另一块 /dev/sdb 只会出现 会出现以下一种状态： 
Power mode was:   IDLE_A
这样会导致在vm中，针对 /dev/sda 记录了两个状态

![Image](https://github.com/user-attachments/assets/3ce6c4cf-0f70-46ee-a1a2-eefbab6c3421)

针对这个情况，我临时 使用了 power="IDLE_A" 进行了过滤
但是我觉得这个并不是一个很好的方法。
我想求问大佬，这种有没有比较好的处理方法。
