### ISSUE TITLE
categraf 通用配置metrics_pass在kafka,es插件不生效

### ISSUE THREAD

**Issue by longjun91** [flashcatcloud/categraf#1232]
### Relevant config.toml

```toml
#es分别使用以下配置不生效
metrics_pass = ["elasticsearch_clusterstats_indices_count"]
metrics_drop = ["elasticsearch_clusterstats_indices_count"]

#kafka分别使用以下配置不生效
metrics_pass = ["kafka_brokers"]
metrics_drop = ["kafka_brokers"]
```

### Logs from categraf

```text
日志仍然输出全量指标，该配置没有起到作用
```

### System info

v0.4.10

### Docker

无

### Steps to reproduce

1.在kafka.toml或elasticsearch.toml中 interval配置下新增metrics_pass
2.使用--test启动categraf
3.查看日志输出 仍是全量指标

### Expected behavior

由于kafka,es 中间件存在topic index等动态增量指标，当采集集群较大，指标量级巨大会消耗较大内存，若存在全局标签处理会更难严重影响采集效率，期望可以修复支持按需采集指标

### Actual behavior

期望可以修复支持按需采集指标
