### ISSUE TITLE
手工运行没问题，systemctl运行就报错 E! failed to get disk usage, mountpoint: /run/credentials/systemd-sysusers.service error: no such file or directory

### ISSUE THREAD

**Issue by usrtax** [flashcatcloud/categraf#193]
手工运行没问题，systemctl运行就报错 E! failed to get disk usage, mountpoint: /run/credentials/systemd-sysusers.service error: no such file or directory

### Relevant config.toml

```toml
[global]
# whether print configs
print_configs = false

# add label(agent_hostname) to series
# "" -> auto detect hostname
# "xx" -> use specified string xx
# "$hostname" -> auto detect hostname
# "$ip" -> auto detect ip
# "$hostname-$ip" -> auto detect hostname and ip to replace the vars
hostname = "$ip-$hostname"

# will not add label(agent_hostname) if true
omit_hostname = false

# s | ms
precision = "ms"

# global collect interval
interval = 15

[global.labels]
source="categraf"
# region = "shanghai"
# env = "localhost"

[writer_opt]
# default: 2000
batch = 2000
# channel(as queue) size
chan_size = 10000

[http]
enable = false
address = ":9100"
print_access = false
run_mode = "release"

[[writers]]
url = "https://n9w.usr.tax/prometheus/v1/write"

# timeout settings, unit: ms
timeout = 5000
dial_timeout = 2500
max_idle_conns_per_host = 100
```

### Logs from categraf

```text
9月 25 02:17:31 qq-cn-shanghai-2-4wYFAP7iw8 systemd[1]: Started categraf.
9月 25 02:17:31 qq-cn-shanghai-2-4wYFAP7iw8 categraf[952624]: 2022/09/25 02:17:31 main.go:118: I! runner.binarydir: /root/user/key/n9
9月 25 02:17:31 qq-cn-shanghai-2-4wYFAP7iw8 categraf[952624]: 2022/09/25 02:17:31 main.go:119: I! runner.hostname: qq-cn-shanghai-2-4wYFAP7iw8
9月 25 02:17:31 qq-cn-shanghai-2-4wYFAP7iw8 categraf[952624]: 2022/09/25 02:17:31 main.go:120: I! runner.fd_limits: (soft=1024, hard=524288)
9月 25 02:17:31 qq-cn-shanghai-2-4wYFAP7iw8 categraf[952624]: 2022/09/25 02:17:31 main.go:121: I! runner.vm_limits: (soft=unlimited, hard=unlimited)
9月 25 02:17:31 qq-cn-shanghai-2-4wYFAP7iw8 categraf[952624]: 2022/09/25 02:17:31 config.go:33: I! tracing disabled
9月 25 02:17:31 qq-cn-shanghai-2-4wYFAP7iw8 categraf[952624]: 2022/09/25 02:17:31 provider.go:63: I! use input provider: []
9月 25 02:17:31 qq-cn-shanghai-2-4wYFAP7iw8 categraf[952624]: 2022/09/25 02:17:31 agent.go:82: I! agent starting
9月 25 02:17:31 qq-cn-shanghai-2-4wYFAP7iw8 categraf[952624]: 2022/09/25 02:17:31 metrics_agent.go:93: I! input: local.cpu started
9月 25 02:17:31 qq-cn-shanghai-2-4wYFAP7iw8 categraf[952624]: 2022/09/25 02:17:31 metrics_agent.go:93: I! input: local.disk started
9月 25 02:17:31 qq-cn-shanghai-2-4wYFAP7iw8 categraf[952624]: 2022/09/25 02:17:31 metrics_agent.go:93: I! input: local.diskio started
9月 25 02:17:31 qq-cn-shanghai-2-4wYFAP7iw8 categraf[952624]: 2022/09/25 02:17:31 ps.go:150: E! failed to get disk usage, mountpoint: /run/credentials>
9月 25 02:17:31 qq-cn-shanghai-2-4wYFAP7iw8 categraf[952624]: 2022/09/25 02:17:31 metrics_agent.go:93: I! input: local.docker started
9月 25 02:17:31 qq-cn-shanghai-2-4wYFAP7iw8 categraf[952624]: 2022/09/25 02:17:31 metrics_agent.go:93: I! input: local.kernel started
9月 25 02:17:31 qq-cn-shanghai-2-4wYFAP7iw8 categraf[952624]: 2022/09/25 02:17:31 metrics_agent.go:93: I! input: local.kernel_vmstat started
9月 25 02:17:31 qq-cn-shanghai-2-4wYFAP7iw8 categraf[952624]: 2022/09/25 02:17:31 metrics_agent.go:93: I! input: local.linux_sysctl_fs started
9月 25 02:17:31 qq-cn-shanghai-2-4wYFAP7iw8 categraf[952624]: 2022/09/25 02:17:31 metrics_agent.go:93: I! input: local.mem started
9月 25 02:17:31 qq-cn-shanghai-2-4wYFAP7iw8 categraf[952624]: 2022/09/25 02:17:31 metrics_agent.go:93: I! input: local.net started
9月 25 02:17:31 qq-cn-shanghai-2-4wYFAP7iw8 categraf[952624]: 2022/09/25 02:17:31 metrics_agent.go:93: I! input: local.netstat started
9月 25 02:17:31 qq-cn-shanghai-2-4wYFAP7iw8 categraf[952624]: 2022/09/25 02:17:31 metrics_agent.go:93: I! input: local.processes started
9月 25 02:17:31 qq-cn-shanghai-2-4wYFAP7iw8 categraf[952624]: 2022/09/25 02:17:31 metrics_agent.go:93: I! input: local.system started
9月 25 02:17:31 qq-cn-shanghai-2-4wYFAP7iw8 categraf[952624]: 2022/09/25 02:17:31 prometheus_scrape.go:14: I! prometheus scraping disabled!
9月 25 02:17:31 qq-cn-shanghai-2-4wYFAP7iw8 categraf[952624]: 2022/09/25 02:17:31 agent.go:93: I! agent started
9月 25 02:17:46 qq-cn-shanghai-2-4wYFAP7iw8 categraf[952624]: 2022/09/25 02:17:46 ps.go:150: E! failed to get disk usage, mountpoint: /run/credentials>
9月 25 02:18:01 qq-cn-shanghai-2-4wYFAP7iw8 categraf[952624]: 2022/09/25 02:18:01 ps.go:150: E! failed to get disk usage, mountpoint: /run/credentials>
9月 25 02:18:16 qq-cn-shanghai-2-4wYFAP7iw8 categraf[952624]: 2022/09/25 02:18:16 ps.go:150: E! failed to get disk usage, mountpoint: /run/credentials>
9月 25 02:18:31 qq-cn-shanghai-2-4wYFAP7iw8 categraf[952624]: 2022/09/25 02:18:31 ps.go:150: E! failed to get disk usage, mountpoint: /run/credentials>
9月 25 02:18:46 qq-cn-shanghai-2-4wYFAP7iw8 categraf[952624]: 2022/09/25 02:18:46 ps.go:150: E! failed to get disk usage, mountpoint: /run/credentials>
9月 25 02:19:01 qq-cn-shanghai-2-4wYFAP7iw8 categraf[952624]: 2022/09/25 02:19:01 ps.go:150: E! failed to get disk usage, mountpoint: /run/credentials>
9月 25 02:19:16 qq-cn-shanghai-2-4wYFAP7iw8 categraf[952624]: 2022/09/25 02:19:16 ps.go:150: E! failed to get disk usage, mountpoint: /run/credentials>
9月 25 02:19:31 qq-cn-shanghai-2-4wYFAP7iw8 categraf[952624]: 2022/09/25 02:19:31 ps.go:150: E! failed to get disk usage, mountpoint: /run/credentials>
9月 25 02:19:46 qq-cn-shanghai-2-4wYFAP7iw8 categraf[952624]: 2022/09/25 02:19:46 ps.go:150: E! failed to get disk usage, mountpoint: /run/credentials>
9月 25 02:20:01 qq-cn-shanghai-2-4wYFAP7iw8 categraf[952624]: 2022/09/25 02:20:01 ps.go:150: E! failed to get disk usage, mountpoint: /run/credentials>
9月 25 02:20:16 qq-cn-shanghai-2-4wYFAP7iw8 categraf[952624]: 2022/09/25 02:20:16 ps.go:150: E! failed to get disk usage, mountpoint: /run/credentials>
9月 25 02:20:31 qq-cn-shanghai-2-4wYFAP7iw8 categraf[952624]: 2022/09/25 02:20:31 ps.go:150: E! failed to get disk usage, mountpoint: /run/credentials>
9月 25 02:20:46 qq-cn-shanghai-2-4wYFAP7iw8 categraf[952624]: 2022/09/25 02:20:46 ps.go:150: E! failed to get disk usage, mountpoint: /run/credentials>
lines 131-174/174 (END)
```

### System info

Ubuntu 22.04.1 LTS 

### Steps to reproduce

1.
2.
3.
...

### Expected behavior

正常监控

### Actual behavior

一直报错

### Additional info

手工运行没问题，systemctl运行就报错
```
[Unit]
Description=categraf
After=network.target

[Service]
Type=simple
ExecStart=/root/user/key/n9/categraf
WorkingDirectory=/root/user/key/n9
PrivateTmp=true
Restart=on-failure
SuccessExitStatus=0
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=categraf

[Install]
WantedBy=multi-user.target
```

cp categraf.service /lib/systemd/system/
systemctl daemon-reload
systemctl enable categraf --now
