### ISSUE TITLE
sql server input 报错

### ISSUE THREAD

**Issue by shawnloong** [flashcatcloud/categraf#225]
### Relevant config.toml

```toml
# # collect interval
# interval = 15

 [[instances]]

## Specify instances to monitor with a list of connection strings.
  ## All connection parameters are optional.
  ## By default, the host is localhost, listening on default port, TCP 1433.
  ##   for Windows, the user is the currently running AD user (SSO).
  ##   See https://github.com/denisenkom/go-mssqldb for detailed connection
  ##   parameters, in particular, tls connections can be created like so:
  ##   "encrypt=true;certificate=<cert>;hostNameInCertificate=<SqlServer host fqdn>"
  # servers = [ ]
servers = [
"Server=192.168.100.44;Port=1433;User Id=[categraf];Password=Mystrongpassword123;app name=master;log=1;",
 ]
  ## Authentication method
  ## valid methods: "connection_string", "AAD"
  # auth_method = "connection_string"

  ## "database_type" enables a specific set of queries depending on the database type. If specified, it replaces azuredb = true/false and query_version = 2
  ## In the config file, the sql server plugin section should be repeated each with a set of servers for a specific database_type.
  ## Possible values for database_type are - "SQLServer" or "AzureSQLDB" or "AzureSQLManagedInstance" or "AzureSQLPool"

  database_type = "SQLServer"

  ## A list of queries to include. If not specified, all the below listed queries are used.
  include_query = []

  ## A list of queries to explicitly ignore.
  exclude_query = ["SQLServerAvailabilityReplicaStates", "SQLServerDatabaseReplicaStates"]

  ## Queries enabled by default for database_type = "SQLServer" are -
  ## SQLServerPerformanceCounters, SQLServerWaitStatsCategorized, SQLServerDatabaseIO, SQLServerProperties, SQLServerMemoryClerks,
  ## SQLServerSchedulers, SQLServerRequests, SQLServerVolumeSpace, SQLServerCpu, SQLServerAvailabilityReplicaStates, SQLServerDatabaseReplicaStates,
  ## SQLServerRecentBackups



  ## Following are old config settings
  ## You may use them only if you are using the earlier flavor of queries, however it is recommended to use
  ## the new mechanism of identifying the database_type there by use it's corresponding queries

  ## Optional parameter, setting this to 2 will use a new version
  ## of the collection queries that break compatibility with the original
  ## dashboards.
  ## Version 2 - is compatible from SQL Server 2012 and later versions and also for SQL Azure DB
  # query_version = 2

  ## Toggling this to true will emit an additional metric called "sqlserver_telegraf_health".
  ## This metric tracks the count of attempted queries and successful queries for each SQL instance specified in "servers".
  ## The purpose of this metric is to assist with identifying and diagnosing any connectivity or query issues.
  ## This setting/metric is optional and is disabled by default.
  # health_metric = false

  ## Possible queries accross different versions of the collectors
  ## Queries enabled by default for specific Database Type

  ## database_type =  SQLServer by default collects the following queries
  ## - SQLServerPerformanceCounters
  ## - SQLServerWaitStatsCategorized
  ## - SQLServerDatabaseIO
  ## - SQLServerProperties
  ## - SQLServerMemoryClerks
  ## - SQLServerSchedulers
  ## - SQLServerRequests
  ## - SQLServerVolumeSpace
  ## - SQLServerCpu
  ## - SQLServerRecentBackups
  ## and following as optional (if mentioned in the include_query list)
  ## - SQLServerAvailabilityReplicaStates
  ## - SQLServerDatabaseReplicaStates

  ## Version 2 by default collects the following queries
  ## Version 2 is being deprecated, please consider using database_type.
  ## - PerformanceCounters
  ## - WaitStatsCategorized
  ## - DatabaseIO
  ## - ServerProperties
  ## - MemoryClerk
  ## - Schedulers
  ## - SqlRequests
  ## - VolumeSpace
  ## - Cpu

  ## Version 1 by default collects the following queries
  ## Version 1 is deprecated, please consider using database_type.
  ## - PerformanceCounters
  ## - WaitStatsCategorized
  ## - CPUHistory
  ## - DatabaseIO
  ## - DatabaseSize
  ## - DatabaseStats
  ## - DatabaseProperties
  ## - MemoryClerk
  ## - VolumeSpace
  ## - PerformanceMetrics
```

### Logs from categraf

```text
0/28 14:13:37 rocketmq.go:275: E! unable to decode topic name list unexpected end of JSON input
0/28 14:13:37 rocketmq.go:51: E! fail to get topic,please check config!
0/28 14:13:38 sqlserver.go:210: E! queryError is  query SQLServerSchedulers failed for server: 192.168.200.44 and database: <empty-database-name> with Error: TLS Handshake failed: tls: server selecte
0/28 14:13:38 sqlserver.go:210: E! queryError is  query SQLServerMemoryClerks failed for server: 192.168.200.44 and database: <empty-database-name> with Error: TLS Handshake failed: tls: server selec
0/28 14:13:38 sqlserver.go:210: E! queryError is  query SQLServerRecentBackups failed for server: 192.168.200.44 and database: <empty-database-name> with Error: TLS Handshake failed: tls: server sele
0/28 14:13:38 sqlserver.go:210: E! queryError is  query SQLServerCpu failed for server: 192.168.100.44 and database: <empty-database-name> with Error: TLS Handshake failed: tls: server selected unsup
0/28 14:13:38 sqlserver.go:210: E! queryError is  query SQLServerVolumeSpace failed for server: 192.168.200.44 and database: <empty-database-name> with Error: TLS Handshake failed: tls: server select
0/28 14:13:38 sqlserver.go:210: E! queryError is  query SQLServerRequests failed for server: 192.168.200.44 and database: <empty-database-name> with Error: TLS Handshake failed: tls: server selected
0/28 14:13:38 sqlserver.go:210: E! queryError is  query SQLServerDatabaseIO failed for server: 192.168.200.44 and database: <empty-database-name> with Error: TLS Handshake failed: tls: server selecte
0/28 14:13:38 sqlserver.go:210: E! queryError is  query SQLServerPerformanceCounters failed for server: 192.168.200.44 and database: <empty-database-name> with Error: TLS Handshake failed: tls: serve
0/28 14:13:38 sqlserver.go:210: E! queryError is  query SQLServerProperties failed for server: 192.168.200.44 and database: <empty-database-name> with Error: TLS Handshake failed: tls: server selecte
0/28 14:13:38 sqlserver.go:210: E! queryError is  query SQLServerWaitStatsCategorized failed for server: 192.168.200.44 and database: <empty-database-name> with Error: TLS Handshake failed: tls: serv
0/28 14:13:52 rocketmq.go:275: E! unable to decode topic name list unexpected end of JSON input
0/28 14:13:52 rocketmq.go:51: E! fail to get topic,please check config!
```

### System info

windows 2008 r2

### Steps to reproduce

1

### Expected behavior

1

### Actual behavior

1
