### ISSUE TITLE
UDP监控有什么方法吗

### ISSUE THREAD

**Issue by liufangpeng** [flashcatcloud/categraf#303]
UDP能使用net_response进行监控吗

**Comment by liufangpeng** [comment]
能同时实现监控TCP和UDP吗我看net_response好像只能二选一

**Comment by xiaoziv** [comment]
配置多个instance即可
```toml
[[instances]]
targets = [
  ":9090"
]

[[instances]]
targets = [
  ":9091"
]
protocol = "tcp"
```
