### ISSUE TITLE
关于 hostpath 挂载根目录 "/" 的问题

### ISSUE THREAD

**Issue by sklun** [flashcatcloud/categraf#353]
直接挂载 "/" 可能不太安全，除 /proc 目录外还需要监控什么路径吗
```yaml
      - hostPath:
          path: /
          type: ""
```

<img width="989" alt="image" src="https://user-images.githubusercontent.com/33173987/218354813-55bc89b3-a62e-44a4-9a3a-bb788ce092c4.png">
