### ISSUE TITLE
kafka采集错误

### ISSUE THREAD

**Issue by carry2017123** [flashcatcloud/categraf#397]
### Relevant config.toml

```toml
[global]
# whether print configs
print_configs = false

# add label(agent_hostname) to series
# "" -> auto detect hostname
# "xx" -> use specified string xx
# "$hostname" -> auto detect hostname
# "$ip" -> auto detect ip
# "$hostname-$ip" -> auto detect hostname and ip to replace the vars
hostname = "$ip"

# will not add label(agent_hostname) if true
omit_hostname = false

# s | ms
precision = "ms"

# global collect interval
interval = 15

# input provider settings; optional: local / http
providers = ["local"]

disable_usage_report = true

[global.labels]
# region = "shanghai"
# env = "localhost"
agent_type="categraf"

[log]
# file_name is the file to write logs to
file_name = "stdout"

# options below will not be work when file_name is stdout or stderr
# max_size is the maximum size in megabytes of the log file before it gets rotated. It defaults to 100 megabytes.
max_size = 100
# max_age is the maximum number of days to retain old log files based on the timestamp encoded in their filename.  
max_age = 1
# max_backups is the maximum number of old log files to retain.  
max_backups = 1
# local_time determines if the time used for formatting the timestamps in backup files is the computer's local time.  
local_time = true
# Compress determines if the rotated log files should be compressed using gzip. 
compress = false

[writer_opt]
batch = 1000
chan_size = 1000000

[[writers]]
url = "http://myurl/insert/0/prometheus"

# Basic auth username
basic_auth_user = ""

# Basic auth password
basic_auth_pass = ""

## Optional headers
# headers = ["X-From", "categraf", "X-Xyz", "abc"]

# timeout settings, unit: ms
timeout = 50000
dial_timeout = 25000
max_idle_conns_per_host = 1000

[http]
enable = false
address = ":9100"
print_access = false
run_mode = "release"

[ibex]
  enable = false
  ## ibex flush interval
  interval = "1000ms"
  ## n9e ibex server rpc address
  Servers = ["127.0.0.1:20090"]
  ## temp script dir
  metaDir = "./meta"

[http_provider]
# HttpRemoteProvider插件，通过Http请求的方式获取Categraf的配置
# 通过设置global中的provider为HttpRemoteProvider启用
# example request: GET /categraf/configs?agent=categraf&host=machine1 HTTP/1.1
# struct of response
# type httpRemoteProviderResponse struct {
#	// version is signature/md5 of current Config, server side should deal with the Version calculate
#	Version string `json:"version"`
#
#	// ConfigMap (InputName -> Config), if version is identical, server side can set Config to nil
#	Configs map[string]cfg.ConfigWithFormat `json:"configs"`
# }
# type ConfigWithFormat struct {
# 	Config string       `json:"config"`
# 	Format ConfigFormat `json:"format"`
# }
# example response:
# {
#  "version": "111",
#  "configs": {
#    "mysql": {
#      "config": "# # collect interval\n# interval = 15\n\n[[ instances ]]\naddress = \"172.33.44.55:3306\"\nusername = \"111\"\npassword = \"2222\"\nlabels = { instance = \"mysql2\"}\nextra_innodb_metrics =true",
#      "format": "toml"
#    }
#  }
#}
#
# remote url
remote_url = "http://localhost:20000/categraf/configs"

# header settings when request config from remote
# headers = ["X-From", "categraf", "X-Xyz", "abc"]

# http basic auth config
# basic_auth_user = ""
# basic_auth_pass = ""

# http timeout in seconds
timeout = 5

# reload interval in seconds
reload_interval = 120

## Optional TLS Config
# use_tls = false
# tls_ca = "/etc/categraf/ca.pem"
# tls_cert = "/etc/categraf/cert.pem"
# tls_key = "/etc/categraf/key.pem"
## Use TLS but skip chain & host verification
# insecure_skip_verify = false

kafka.toml配置：
[[instances]]
labels = { instance = "10.98.32.66:8101",business_name = "test",ip = "10.98.32.66",port = "8101",developer = "" }
kafka_uris = [ "10.98.32.66:8101" ]
metrics_pass = [ ]
```

### Logs from categraf

```text
level=debug msg="describing consumergroups for broker" broker=1
level=debug msg="fetching offsets for broker/group" broker=1 group=product_data_sortation_bypass_dev
level=debug msg="describing consumergroups for broker" broker=2
level=error msg="Error fetching offset for consumergroup" group=product_data_sortation_bypass_dev err=EOF
level=debug msg="fetching offsets for broker/group" broker=1 group=tahm_inquiry_form_auth_transfer_b2b_inquiry
level=error msg="Error fetching offset for consumergroup" group=tahm_inquiry_form_auth_transfer_b2b_inquiry err=EOF
level=debug msg="fetching offsets for broker/group" broker=1 group=product_data_sync_test1
level=error msg="Error fetching offset for consumergroup" group=product_data_sync_test1 err=EOF
level=debug msg="fetching offsets for broker/group" broker=1 group=product_sku_new_v2_test
level=error msg="Error fetching offset for consumergroup" group=product_sku_new_v2_test err="write tcp 10.98.32.66:61290->10.98.32.72:8101: write: broken pipe"
level=debug msg="fetching offsets for broker/group" broker=1 group=tahm-product-test
level=error msg="Error fetching offset for consumergroup" group=tahm-product-test err="write tcp 10.98.32.66:61290->10.98.32.72:8101: write: broken pipe"
level=debug msg="fetching offsets for broker/group" broker=1 group=tahm_product_sku_transfer_dev
level=error msg="Error fetching offset for consumergroup" group=tahm_product_sku_transfer_dev err="write tcp 10.98.32.66:61290->10.98.32.72:8101: write: broken pipe"
level=debug msg="fetching offsets for broker/group" broker=1 group=product_plugin_test
level=error msg="Error fetching offset for consumergroup" group=product_plugin_test err="write tcp 10.98.32.66:61290->10.98.32.72:8101: write: broken pipe"
level=debug msg="fetching offsets for broker/group" broker=1 group=product_data_source_table_bypass_dev
level=error msg="Error fetching offset for consumergroup" group=product_data_source_table_bypass_dev err="write tcp 10.98.32.66:61290->10.98.32.72:8101: write: broken pipe"
level=debug msg="fetching offsets for broker/group" broker=1 group=product_data_product_dev
level=error msg="Error fetching offset for consumergroup" group=product_data_product_dev err="write tcp 10.98.32.66:61290->10.98.32.72:8101: write: broken pipe"
level=debug msg="fetching offsets for broker/group" broker=1 group=tahm_stock_transfer_transfer_test
level=error msg="Error fetching offset for consumergroup" group=tahm_stock_transfer_transfer_test err="write tcp 10.98.32.66:61290->10.98.32.72:8101: write: broken pipe"
level=debug msg="fetching offsets for broker/group" broker=1 group=tahm-product-pro_dev
level=error msg="Error fetching offset for consumergroup" group=tahm-product-pro_dev err="write tcp 10.98.32.66:61290->10.98.32.72:8101: write: broken pipe"
level=debug msg="fetching offsets for broker/group" broker=2 group=keyujun
level=error msg="Error fetching offset for consumergroup" group=keyujun err=EOF
level=debug msg="fetching offsets for broker/group" broker=2 group=product_data_product_test1
level=error msg="Error fetching offset for consumergroup" group=product_data_product_test1 err=EOF
level=debug msg="fetching offsets for broker/group" broker=2 group=product_data_sortation_bypass_test1
level=error msg="Error fetching offset for consumergroup" group=product_data_sortation_bypass_test1 err=EOF
level=debug msg="fetching offsets for broker/group" broker=2 group=pot_test
level=error msg="Error fetching offset for consumergroup" group=pot_test err=EOF
level=debug msg="fetching offsets for broker/group" broker=2 group=pcq_product_test
level=error msg="Error fetching offset for consumergroup" group=pcq_product_test err="write tcp 10.98.32.66:37422->10.98.32.73:8101: write: broken pipe"
level=debug msg="fetching offsets for broker/group" broker=2 group=product_plugin_dev_1
level=error msg="Error fetching offset for consumergroup" group=product_plugin_dev_1 err="write tcp 10.98.32.66:37422->10.98.32.73:8101: write: broken pipe"
level=debug msg="fetching offsets for broker/group" broker=2 group=tahm_product_transfer_test
level=error msg="Error fetching offset for consumergroup" group=tahm_product_transfer_test err="write tcp 10.98.32.66:37422->10.98.32.73:8101: write: broken pipe"
level=debug msg="fetching offsets for broker/group" broker=2 group=tahm_stock_transfer_item_transfer_test
level=error msg="Error fetching offset for consumergroup" group=tahm_stock_transfer_item_transfer_test err="write tcp 10.98.32.66:37422->10.98.32.73:8101: write: broken pipe"
level=debug msg="fetching offsets for broker/group" broker=2 group=pcq_test
level=error msg="Error fetching offset for consumergroup" group=pcq_test err="write tcp 10.98.32.66:37422->10.98.32.73:8101: write: broken pipe"
level=debug msg="fetching offsets for broker/group" broker=2 group=product_data_sync_dev
level=error msg="Error fetching offset for consumergroup" group=product_data_sync_dev err="write tcp 10.98.32.66:37422->10.98.32.73:8101: write: broken pipe"
level=debug msg="fetching offsets for broker/group" broker=2 group=tahm_product_sku_transfer_test
level=error msg="Error fetching offset for consumergroup" group=tahm_product_sku_transfer_test err="write tcp 10.98.32.66:37422->10.98.32.73:8101: write: broken pipe"
level=debug msg="fetching offsets for broker/group" broker=2 group=tahm_product_sku_attribute_value_transfer_test
level=error msg="Error fetching offset for consumergroup" group=tahm_product_sku_attribute_value_transfer_test err="write tcp 10.98.32.66:37422->10.98.32.73:8101: write: broken pipe"
level=debug msg="fetching offsets for broker/group" broker=2 group=tahm_product_transfer_dev
level=error msg="Error fetching offset for consumergroup" group=tahm_product_transfer_dev err="write tcp 10.98.32.66:37422->10.98.32.73:8101: write: broken pipe"
level=debug msg="fetching offsets for broker/group" broker=2 group=tahm_product_sku_attribute_value_transfer_dev
level=error msg="Error fetching offset for consumergroup" group=tahm_product_sku_attribute_value_transfer_dev err="write tcp 10.98.32.66:37422->10.98.32.73:8101: write: broken pipe"
level=debug msg="fetching offsets for broker/group" broker=2 group=product_data_stock_dev
level=error msg="Error fetching offset for consumergroup" group=product_data_stock_dev err="write tcp 10.98.32.66:37422->10.98.32.73:8101: write: broken pipe"
level=debug msg="fetching offsets for broker/group" broker=2 group=aurogon-stock-test
level=error msg="Error fetching offset for consumergroup" group=aurogon-stock-test err="write tcp 10.98.32.66:37422->10.98.32.73:8101: write: broken pipe"
level=debug msg="fetching offsets for broker/group" broker=2 group=product_data_source_table_bypass_test1
level=error msg="Error fetching offset for consumergroup" group=product_data_source_table_bypass_test1 err="write tcp 10.98.32.66:37422->10.98.32.73:8101: write: broken pipe"
level=debug msg="fetching offsets for broker/group" broker=2 group=product_data_sortation_test1
level=error msg="Error fetching offset for consumergroup" group=product_data_sortation_test1 err="write tcp 10.98.32.66:37422->10.98.32.73:8101: write: broken pipe"
level=debug msg="fetching offsets for broker/group" broker=2 group=product_data_sortation_dev
level=error msg="Error fetching offset for consumergroup" group=product_data_sortation_dev err="write tcp 10.98.32.66:37422->10.98.32.73:8101: write: broken pipe"
level=debug msg="fetching offsets for broker/group" broker=2 group=tahm_stock_transfer_item_transfer_dev
level=error msg="Error fetching offset for consumergroup" group=tahm_stock_transfer_item_transfer_dev err="write tcp 10.98.32.66:37422->10.98.32.73:8101: write: broken pipe"
level=info msg="Calculating consumergroup lag"
level=debug msg="waiting for consumergroup lag estimation metric generation to complete"
```

### System info

kafka版本：2.12-1.1.0

### Steps to reproduce

1.配置config如上面的文件
2.配置kafka.toml如上面我配置
3../categraf --test --inputs kafka 启动可以复现
...

### Expected behavior

1.配置config如上面的文件
2.配置kafka.toml如上面我配置
3../categraf --test --inputs kafka 启动可以复现
...

### Actual behavior

1.配置config如上面的文件
2.配置kafka.toml如上面我配置
3../categraf --test --inputs kafka 启动可以复现
...
