### ISSUE TITLE
failed to get net sockstat6:  open /proc/net/sockstat6: no such file or directory

### ISSUE THREAD

**Issue by sweetweapen** [flashcatcloud/categraf#426]
### Relevant config.toml

```toml
[global]
# whether print configs
print_configs = false

# add label(agent_hostname) to series
# "" -> auto detect hostname
# "xx" -> use specified string xx
# "$hostname" -> auto detect hostname
# "$ip" -> auto detect ip
# "$hostname-$ip" -> auto detect hostname and ip to replace the vars
hostname = "$ip"

# will not add label(agent_hostname) if true
omit_hostname = false

# s | ms
precision = "ms"

# global collect interval
interval = 15

# input provider settings; optional: local / http
providers = ["local"]

disable_usage_report = true

# [global.labels]
# region = "shanghai"
# env = "localhost"

[log]
# file_name is the file to write logs to
file_name = "stdout"

# options below will not be work when file_name is stdout or stderr
# max_size is the maximum size in megabytes of the log file before it gets rotated. It defaults to 100 megabytes.
max_size = 100
# max_age is the maximum number of days to retain old log files based on the timestamp encoded in their filename.
max_age = 1
# max_backups is the maximum number of old log files to retain.
max_backups = 1
# local_time determines if the time used for formatting the timestamps in backup files is the computer's local time.
local_time = true
# Compress determines if the rotated log files should be compressed using gzip.
compress = false

[writer_opt]
batch = 1000
chan_size = 1000000

[[writers]]
url = "http://127.0.0.1:18000/prometheus/v1/write"

# Basic auth username
basic_auth_user = ""

# Basic auth password
basic_auth_pass = ""

## Optional headers
# headers = ["X-From", "categraf", "X-Xyz", "abc"]

# timeout settings, unit: ms
timeout = 5000
dial_timeout = 2500
max_idle_conns_per_host = 100

[http]
enable = false
address = ":9100"
print_access = false
run_mode = "release"

[ibex]
enable = false
## ibex flush interval
interval = "1000ms"
## n9e ibex server rpc address
servers = ["127.0.0.1:20090"]
## temp script dir
meta_dir = "./meta"

[heartbeat]
enable = false

# report os version cpu.util mem.util metadata
url = "http://127.0.0.1:17000/v1/n9e/heartbeat"

# interval, unit: s
interval = 10

# Basic auth username
basic_auth_user = ""

# Basic auth password
basic_auth_pass = ""

## Optional headers
# headers = ["X-From", "categraf", "X-Xyz", "abc"]

# timeout settings, unit: ms
timeout = 5000
dial_timeout = 2500
max_idle_conns_per_host = 100
```

### Logs from categraf

```text
categraf[53063]: 2023/03/26 16:46:25 sockstat.go:59: E! failed to get net sockstat6:  open /proc/net/sockstat6: no such file or directory
```

### System info

categraf v0.2.35  linux（未开启ipv6）

### Steps to reproduce

1. 升级categraf至最新版本0.2.35
2. 重启categraf
3. 如果没有启动ipv6相关，观察日志，会有相关报错

### Expected behavior

默认不探测ipv6状态，categraf正常启动无报错日志

### Actual behavior

探测ipv6 socket status ，持续输出错误日志

### Additional info

通过配置input.sockstat/sockstat.toml配置文件关闭ipv6状态探测，或者默认不探测ipv6，需要时才打开，一般情况下很少用到ipv6
