### ISSUE TITLE
mtail 采集指标中断，categraf 无错误日志输出，能否提供些排查思路？

### ISSUE THREAD

**Issue by JalanJiang** [flashcatcloud/categraf#429]
### Relevant config.toml

```toml
[global]
# whether print configs
print_configs = false

# add label(agent_hostname) to series
# "" -> auto detect hostname
# "xx" -> use specified string xx
# "$hostname" -> auto detect hostname
# "$ip" -> auto detect ip
# "$hostname-$ip" -> auto detect hostname and ip to replace the vars
hostname = ""

# will not add label(agent_hostname) if true
omit_hostname = false

# s | ms
precision = "ms"

# global collect interval
interval = 15

# input provider settings; optional: local / http
providers = ["local"]

disable_usage_report = true

# [global.labels]
# region = "shanghai"
# env = "localhost"

[log]
# file_name is the file to write logs to
file_name = "stderr"

# options below will not be work when file_name is stdout or stderr
# max_size is the maximum size in megabytes of the log file before it gets rotated. It defaults to 100 megabytes.
max_size = 100
# max_age is the maximum number of days to retain old log files based on the timestamp encoded in their filename.
max_age = 1
# max_backups is the maximum number of old log files to retain.
max_backups = 1
# local_time determines if the time used for formatting the timestamps in backup files is the computer's local time.
local_time = true
# Compress determines if the rotated log files should be compressed using gzip.
compress = false

[writer_opt]
batch = 1000
chan_size = 1000000

[[writers]]
url = "http://159.138.205.13:19000/prometheus/v1/write"

# Basic auth username
basic_auth_user = ""

# Basic auth password
basic_auth_pass = ""

## Optional headers
# headers = ["X-From", "categraf", "X-Xyz", "abc"]

# timeout settings, unit: ms
timeout = 5000
dial_timeout = 2500
max_idle_conns_per_host = 100

[http]
enable = false
address = ":9100"
print_access = false
run_mode = "release"

[ibex]
enable = false
## ibex flush interval
interval = "1000ms"
## n9e ibex server rpc address
Servers = ["127.0.0.1:20090"]
## temp script dir
metaDir = "./meta"
```

### Logs from categraf

```text
无
```

### System info

Linux ru01-ad-phpui00 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### Steps to reproduce

1. 安装采集器 categraf
2. 配置 mtail，配置如下：
```
[[instances]]
progs = "/home/work/categraf/progs/request.mtail"
logs = ["/home/work/odp3/log/ad-appui/Bingo2Projects/sug/sug.log"]
override_timezone = "Asia/Shanghai"
emit_metric_timestamp = "true"
```

```
counter offer_request_total
counter offer_recall_total


/action=suggestion/ {

    /^/ +
    /\S+ \d+ (?P<timestamp>\d+ \d{2}:\d{2}:\d{2}) .*/ +
    /$/ {
        strptime($timestamp, "20060102 15:04:05") # 真实使用需放开该条注释

        /^/ +
        /.*clickids=\[(?P<click_id>\S*)\].*/ +
        /$/ {

            offer_request_total++

            $click_id != "" {

                offer_recall_total++

            }

        }

    }
}
```
3. 启动采集器。一开始指标采集正常，大约 1 小时后中断，能稳定复现

### Expected behavior

mtail 规则如果正常，metrics 应该不会中断。已观察机器 CPU、内存、磁盘等各项资源指标仍有富裕

### Actual behavior

指标采集中断，metrics 消失：
![image](https://user-images.githubusercontent.com/7787716/227914878-d0926a37-16d1-4120-ba1d-9532f096381c.png)

debug 和 test 模式下 mtail 表现正常，但会出现重复 metrics 问题，如图：
![image](https://user-images.githubusercontent.com/7787716/227914681-a395bdfb-dbe8-428c-ad83-582c41c5a638.png)
![image](https://user-images.githubusercontent.com/7787716/227915132-e341acf1-524f-48ea-8c83-168c90da901f.png)
