### ISSUE TITLE
E! input: local.oracle not supported

### ISSUE THREAD

**Issue by Jasonzhaochen** [flashcatcloud/categraf#437]
### Relevant config.toml

```toml
[global]
# whether print configs
print_configs = false

# add label(agent_hostname) to series
# "" -> auto detect hostname
# "xx" -> use specified string xx
# "$hostname" -> auto detect hostname
# "$ip" -> auto detect ip
# "$hostname-$ip" -> auto detect hostname and ip to replace the vars
hostname = ""

# will not add label(agent_hostname) if true
omit_hostname = false

# s | ms
precision = "ms"

# global collect interval
interval = 15

# input provider settings; optional: local / http
providers = ["local"]

disable_usage_report = true

# [global.labels]
# region = "shanghai"
# env = "localhost"

[log]
# file_name is the file to write logs to
file_name = "stdout"

# options below will not be work when file_name is stdout or stderr
# max_size is the maximum size in megabytes of the log file before it gets rotated. It defaults to 100 megabytes.
max_size = 100
# max_age is the maximum number of days to retain old log files based on the timestamp encoded in their filename.
max_age = 1
# max_backups is the maximum number of old log files to retain.
max_backups = 1
# local_time determines if the time used for formatting the timestamps in backup files is the computer's local time.
local_time = true
# Compress determines if the rotated log files should be compressed using gzip.
compress = false

[writer_opt]
batch = 1000
chan_size = 1000000

[[writers]]
url = "http://127.0.0.1:19000/prometheus/v1/write"

# Basic auth username
basic_auth_user = ""

# Basic auth password
basic_auth_pass = ""

## Optional headers
# headers = ["X-From", "categraf", "X-Xyz", "abc"]

# timeout settings, unit: ms
timeout = 5000
dial_timeout = 2500
max_idle_conns_per_host = 100

[http]
enable = false
address = ":9100"
print_access = false
run_mode = "release"

[ibex]
enable = false
## ibex flush interval
interval = "1000ms"
## n9e ibex server rpc address
servers = ["127.0.0.1:20090"]
## temp script dir
meta_dir = "./meta"

[heartbeat]
enable = false

# report os version cpu.util mem.util metadata
url = "http://127.0.0.1:17000/v1/n9e/heartbeat"

# interval, unit: s
interval = 10

# Basic auth username
basic_auth_user = ""

# Basic auth password
basic_auth_pass = ""

## Optional headers
# headers = ["X-From", "categraf", "X-Xyz", "abc"]

# timeout settings, unit: ms
timeout = 5000
dial_timeout = 2500
max_idle_conns_per_host = 100
```

### Logs from categraf

```text
➜  categraf-v0.2.35-linux-amd64 ./categraf -debug -test -inputs oracle
2023/03/31 17:35:58 I! tracing disabled
2023/03/31 17:35:58 main.go:128: I! runner.binarydir: /opt/nightingale/categraf-v0.2.35-linux-amd64
2023/03/31 17:35:58 main.go:129: I! runner.hostname: oracle.mylab
2023/03/31 17:35:58 main.go:130: I! runner.fd_limits: (soft=262144, hard=262144)
2023/03/31 17:35:58 main.go:131: I! runner.vm_limits: (soft=unlimited, hard=unlimited)
2023/03/31 17:35:58 provider.go:69: I! use input provider: [local]
2023/03/31 17:35:58 traces_agent.go:19: I! traces agent disabled!
2023/03/31 17:35:58 prometheus_agent.go:19: I! prometheus scraping disabled!
2023/03/31 17:35:58 ibex_agent.go:19: I! ibex agent disabled!
2023/03/31 17:35:58 agent.go:39: I! agent starting
2023/03/31 17:35:58 metrics_agent.go:154: E! input: local.oracle not supported
2023/03/31 17:35:58 agent.go:47: I! [*agent.MetricsAgent] started
2023/03/31 17:35:58 agent.go:50: I! agent started
```

### System info

categraf v0.2.35-08e62eb4111eec058e86ef591efa07ff02dc4b02, CentOS Stream release 8, kernel 4.18.0-383.el8.x86_64, Oracle 19c

### Steps to reproduce

Run command below, then you can see the error in the log.

./categraf -debug -test -inputs oracle

I have double-checked my oracle database connectivity information in oracle.toml file. They are correct.

### Expected behavior

Expect categraf to be able to capture the metrics defined in metrics.toml.

### Actual behavior

It says Oracle not supported in the log
