### ISSUE TITLE
ntp 超时时间参数配置吗？

### ISSUE THREAD

**Issue by shawnloong** [flashcatcloud/categraf#438]
### Relevant config.toml

```toml
# # collect interval
 interval = 15

 # ntp servers
 ntp_servers = ["cn.pool.ntp.org"]
```

### Logs from categraf

```text
ntp.go:43: E! failed to connect ntp server: cn.pool.ntp.org error: read udp 192.168.x.x:64820->5.79.108.34:123: i/o timeout
```

### System info

centos 6.9

### Steps to reproduce

[1.
2.
3.
...
](ntp.go:43: E! failed to connect ntp server: cn.pool.ntp.org error: read udp 192.168.10.147:64820->5.79.108.34:123: i/o timeout)

### Expected behavior

ntp.go:43: E! failed to connect ntp server: cn.pool.ntp.org error: read udp 192.168.x.xx:64820->5.79.108.34:123: i/o timeout### 

### Actual behavior

ntp.go:43: E! failed to connect ntp server: cn.pool.ntp.org error: read udp 192.168.x.x:64820->5.79.108.34:123: i/o timeout
