### ISSUE TITLE
local.netstat 获取指标报错

### ISSUE THREAD

**Issue by qifenggang** [flashcatcloud/categraf#458]
### Relevant config.toml

```toml
版本：categraf-v0.2.35-linux-amd64
cat conf/input.netstat/netstat.toml
# # collect interval
# interval = 15

## if machine has many network connections, use this plugin may exhaust your cpu resource, diable connection stat to avoid this
disable_connection_stats = false

tcp_ext = true
ip_ext = true


tcp_ext 和 ip_ext 开启之后，启动如下报错：
```

### Logs from categraf

```text
2023/04/13 17:49:52 metrics_reader.go:69: E! local.netstat : gather metrics panic: &{local.netstat 0xc000f22dc0 0xc0000c3860 0 {{} 0 0}} /opt/hostedtoolcache/go/1.19.7/x64/src/runtime/panic.go:260 (0x450c15)
/opt/hostedtoolcache/go/1.19.7/x64/src/runtime/signal_unix.go:835 (0x450be5)
/home/runner/work/categraf/categraf/inputs/netstat/netstat.go:167 (0x19f5971)
/home/runner/work/categraf/categraf/inputs/netstat/netstat.go:34 (0x19f31da)
/home/runner/work/categraf/categraf/inputs/inputs.go:33 (0x367a204)
/home/runner/work/categraf/categraf/agent/metrics_reader.go:75 (0x367a1ca)
/home/runner/work/categraf/categraf/agent/metrics_reader.go:55 (0x3679f89)
/opt/hostedtoolcache/go/1.19.7/x64/src/runtime/asm_amd64.s:1594 (0x46ea00)
```

### System info

OS:CentOS Linux release 7.9.2009 (Core)   

### Steps to reproduce

1.
2.
3.
...

### Expected behavior

no

### Actual behavior

no
