### ISSUE TITLE
监控获取到的http_response_code和实际请求到的http_response_code不一致

### ISSUE THREAD

**Issue by shaojiechao** [flashcatcloud/categraf#460]
### Relevant config.toml

```toml
[[instances]]
targets = [ "http://docs.xx.xx.tech",
            "http://docsapi.xx.xx.tech"]

# # append some labels for series
# labels = { region="cloud", product="n9e" }

# # interval = global.interval * interval_times
 interval_times = 1

## HTTP Request Method
 method = "GET"

## Set response_timeout (default 5 seconds)
 response_timeout = "5s"
```

### Logs from categraf

```text
没有错误日志
```

### System info

categraf-v0.2.32

### Steps to reproduce

以上两个url在监控页面上查询http_response_response_code{target=~"http://docs.xx.xxtech"}返回值一直是404

### Expected behavior

预期返回值是200

### Actual behavior

通过curl -XGET -I http://docs.xx.xxtech实际返回值是200
