### ISSUE TITLE
categraf cloudwatch 采集 AWS 服务指标问题

### ISSUE THREAD

**Issue by cataglyphis** [flashcatcloud/categraf#467]
### Relevant config.toml

```toml
[[instances]]
region="us-west-1"
endpoint="https://monitoring.us-west-1.amazonaws.com"
access_key="***"
secret_key="***"
period="5m"
delay="10m"
interval = "5m"
cache_ttl="1h"
timeout="5s"
ratelimit = 50
batch_size = 100

namespaces=["AWS/RDS"]
statistic_include = ["average"]

[[inputs.cloudwatch.metrics]]
  namespace = "AWS/RDS"
  names = ["SwapUsage"]
  statistic_include = ["average"]

  [[inputs.cloudwatch.metrics.dimensions]]
    name = "DBInstanceIdentifier"
    value = "postgresql"
```

### Logs from categraf

```text
...
cloudwatch_aws_rds_ebs_byte_balance%_average agent_hostname=jump-server db_instance_identifier=postgresql namespace=AWS/RDS region=us-west-1 100
cloudwatch_aws_rds_network_receive_throughput_average agent_hostname=jump-server engine_name=postgres namespace=AWS/RDS region=us-west-1 20989.753938460508
...
```

### System info

categraf 0.2.39

### Steps to reproduce

1. 配置 aws 插件下的 cloud.toml
2. 运行 categraf debug 模式，观察 console 中打印的采集到的指标

### Expected behavior

采集 AWS 上数据库相关的 metrics，限制 namespace 为 AWS/RDS，在 debug 的时候希望仅采集 `SwapUsage` 指标。由于 RDS 下面有多个数据库实例，希望当前仅采集 postgresql 的数据，按上面方式进行配置后，发现仍然采集到的是所有数据。

### Actual behavior

限制了仅采集 `SwapUsage`，但仍然采集到所有的指标，且 `inputs.cloudwatch.metrics.dimensions` 限制不生效
