### ISSUE TITLE
ping监控配置timeout为小于1的数值时，引发panic错误，导致categraf崩溃

### ISSUE THREAD

**Issue by wknb** [flashcatcloud/categraf#487]
### Relevant config.toml

```toml
[[instances]]
targets = [ 
      "147.147.147.147",    # 目标IP或域名
]   
count = 10          # 数据包数量
ping_interval = 0.5  # ttl生存时间
timeout = 0.5          # 超时间隔
labels = { project="测试2", type="ping"}
```

### Logs from categraf

```text
...
non-positive interval for NewTicker

goroutime 119 [running]:
time.NewTicker(0x0?)
...
```

### System info

centos7

### Steps to reproduce

1.配置ping监控的timeout为小于1的数值，比如:0.5
2.启动categraf
3.报错...

### Expected behavior

超时时间设置为0.5，采集ping监控数据

### Actual behavior

触发panic。
问题排查：
分析源代码，当timeout配置成0.5之后，计算的ins.calcTimeout就会变成0，引发panic，导致后续程序报错
关键代码：
categraf/inputs/ping/ping.go    59行
	if ins.Timeout == 0 {
		ins.calcTimeout = time.Duration(3) * time.Second
	} else {
		ins.calcTimeout = time.Duration(ins.Timeout) * time.Second
	}
