### ISSUE TITLE
 E! failed to exec jstat: exit status 1

### ISSUE THREAD

**Issue by sx2714732** [flashcatcloud/categraf#561]
### Relevant config.toml

```toml
[[instances]]
# # executable name (ie, pgrep <search_exec_substring>)
search_exec_substring = "java"

# # pattern as argument for pgrep (ie, pgrep -f <search_cmdline_substring>)
# search_cmdline_substring = "n9e server"

# # windows service name
# search_win_service = ""

# # search process with specific user, option with exec_substring or cmdline_substring
# search_user = "root"

# # append some labels for series
labels = {name="java" }
#labels = { region="cloud", product="n9e",name="" }

# # interval = global.interval * interval_times
# interval_times = 1

# # mode to use when calculating CPU usage. can be one of 'solaris' or 'irix'
mode = "irix"

# sum of threads/fd/io/cpu/mem, min of uptime/limit
gather_total = true

# will append pid as tag
gather_per_pid = true

#  gather jvm metrics only when jstat is ready
 gather_more_metrics = [
     "threads",
     "fd",
     "io",
     "uptime",
     "cpu",
     "mem",
     "limit",
     "jvm"
 ]
```

### Logs from categraf

```text
2023/07/07 11:20:56 procstat.go:395: E! failed to exec jstat: exit status 1
```

### System info

categraf-v0.3.5,Docker version 18.03.0-ce

### Steps to reproduce

1.docker服务
2.监控java进程
3.报错，failed to exec jstat: exit status 1，jstat失败
...

### Expected behavior

no errors

### Actual behavior

categraf日志报错 2023/07/07 11:20:56 procstat.go:395: E! failed to exec jstat: exit status 1
 procstat.go395行execJstat(pid PID)方法报错
