### ISSUE TITLE
虚拟机有VIP时采集到VIP没采集到真实IP

### ISSUE THREAD

**Issue by nondevops** [flashcatcloud/categraf#580]
### Relevant config.toml

```toml
[global]
# whether print configs
print_configs = false

# add label(agent_hostname) to series
# "" -> auto detect hostname
# "xx" -> use specified string xx
# "$hostname" -> auto detect hostname
# "$ip" -> auto detect ip
# "$hostname-$ip" -> auto detect hostname and ip to replace the vars
hostname = "$hostname-$ip"
```

### Logs from categraf

```text
暂不需要
```

### System info

CentOS Linux release 7.8.2003 (Core)

### Steps to reproduce

虚拟机有VIP时采集到VIP没采集到真实IP，实际诉求需要采集到真实IP，使其$hostname-$ip的值真实有效。

### Expected behavior

虚拟机有VIP时采集到VIP没采集到真实IP，实际诉求需要采集到真实IP，使其$hostname-$ip的值真实有效。

### Actual behavior

虚拟机有VIP时采集到VIP没采集到真实IP，实际诉求需要采集到真实IP，使其$hostname-$ip的值真实有效。
