### ISSUE TITLE
window上内存泄漏

### ISSUE THREAD

**Issue by allenz92** [flashcatcloud/categraf#621]
### Relevant config.toml

```toml
# # collect interval
interval = 30

[[instances]]
# # windows service name
search_win_service = "InfraCategraf"

# # append some labels for series
# labels = { region="cloud", product="n9e" }

# # interval = global.interval * interval_times
# interval_times = 1

# sum of threads/fd/io/cpu/mem, min of uptime/limit
gather_total = true

#  gather jvm metrics only when jstat is ready
gather_more_metrics = [
     "threads",
#     "fd",
     "io",
     "uptime",
     "cpu",
     "mem",
#     "limit",
#     "jvm"
]

```

### Logs from categraf

```text
不涉及
```

### System info

Windows server 2008 r2 / Windows server 2012 r2 / Windows server 2016

### Steps to reproduce

在windows上通过
```
categraf.exe  --win-service-name=`"InfraCategraf`" --win-service-desc=`"Categraf Agent`" --win-service-install
```
安装

### Expected behavior

内存占用稳定

### Actual behavior

通过procstat监控内存占用，查看procstat_mem_usage_total一直递增不减少，最大的已经占用到2G内存了
![](https://github.com/allenz92/img/blob/master/sn2.png?raw=true)
