### ISSUE TITLE
mem_vmalloc_chunk指标的解读

### ISSUE THREAD

**Issue by strongit** [flashcatcloud/categraf#638]
### Relevant config.toml

```toml
[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = true

[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]

[[inputs.diskio]]

[[inputs.mem]]

[[inputs.processes]]

[[inputs.system]]
  fielddrop = ["uptime_format"]

[[inputs.net]]
  ignore_protocol_stats = true
```

### Logs from categraf

```text
无
```

### System info

Linux 3.10.0-957.el7.x86_64

### Steps to reproduce

1.
2.
3.
...

### Expected behavior

<img width="867" alt="image" src="https://github.com/flashcatcloud/categraf/assets/11691213/9efedd6b-1f75-456e-9ce3-67ee3117ec75">

### Actual behavior

获取的数据代表的是系统中可以用于vmalloc的最大连续物理内存块的大小，实际物理机未达到T级别
