### ISSUE TITLE
升级到v0.3.27后，snmp采集时间序列会断断续续，使用0.3.25是正常的

### ISSUE THREAD

**Issue by kevinwangzq** [flashcatcloud/categraf#639]
### Relevant config.toml

```toml
interval = 30

[[instances]]
agents = [
]

timeout = "30s"
version = 2
community = "public"
agent_host_tag = "agent_host"
retries = 1

[[instances.field]]
oid = "1.3.6.1.4.1.674.10892.5.2.1.0"
name = "globalSystemStatus"

[[instances.field]]
oid = "1.3.6.1.4.1.674.10892.5.2.3.0"
name = "globalStorageStatus"

[[instances.field]]
oid = "1.3.6.1.4.1.674.10892.5.2.4.0"
name = "systemPowerState"

[[instances.table]]
oid = ".1.3.6.1.4.1.674.10892.5.4.1100.30"
name = "processor"
inherit_tags = ["processor"]
```

### Logs from categraf

```text
ins: gathering table processor error: performing bulk walk for field processorDeviceStateCapabilities: request timeout (after 1 retries)
ins: gathering table processor error: performing bulk walk for field processorDeviceStatus: request timeout (after 1 retries)
```

### System info

categraf 0.3.27 , Centos 7.9，n9e v6.0.2

### Steps to reproduce

1.
2.
3.
...

### Expected behavior

![16939068495681](https://github.com/flashcatcloud/categraf/assets/131642730/e4e34b75-99ea-47dd-809c-88739bc394b0)
![20230905172526](https://github.com/flashcatcloud/categraf/assets/131642730/323a3b2a-d243-4028-a175-d952debd4dec)
![20230905173605](https://github.com/flashcatcloud/categraf/assets/131642730/713e53d8-7249-4294-89ba-46993abfafda)

### Actual behavior

在categraf配置文件、snmp mibs包，都相同为更改的情况下，升级到0.3.27版本后就会出现，回退到0.3.25版本就是正常的。
