### ISSUE TITLE
categraf的http_response.toml采集器中，如果请求时表单类型，那么body应该如何配置参数。

### ISSUE THREAD

**Issue by IT-Forerunner** [flashcatcloud/categraf#645]
例如：
headers = ["Content-Type", "multipart/form-data"]
 body = '''
{ }
'''

body如果要传参
name 值为name1  
password  值为 123456 

应该如何正确配置

**Comment by UlricQin** [comment]
这是http知识了，最简单的是你可以用chrome开发者工具看看你们的登录页面发的请求是什么，如果是form-data方式，body里应该是：

```toml
body = '''
name=name1&password=123456
'''
```
