### ISSUE TITLE
Categraf采集Mysql指标信息偶现长时间挂起/无响应现象

### ISSUE THREAD

**Issue by Jerry-fmcheng** [flashcatcloud/categraf#646]
### Relevant config.toml

```toml
input.mysql/mysql.toml配置关键信息如下(IP地址等信息使用xx代替)：
# collect interval
interval = 300

[[instances]]
 address = "xx:xx:xx:xx:3306"
 username = "xxxx"
 password = "xxxx"

# set tls=custom to enable tls
 parameters = "tls=false"

 extra_status_metrics = true
 extra_innodb_metrics = false
 gather_processlist_processes_by_state = false
 gather_processlist_processes_by_user = false
 gather_schema_size = true
 gather_table_size = true
 gather_system_table_size = false
 gather_slave_status = true

# timeout
 timeout_seconds = 60

# interval = global.interval * interval_times
 interval_times = 1

# Optional TLS Config
 use_tls = false
# Use TLS but skip chain & host verification
 insecure_skip_verify = true
```

### Logs from categraf

```text
2023/09/08 18:06:48 schema_size.go:18: E! failed to get schema size: invalid connection
2023/09/08 18:06:48 table_size.go:26: E! failed to get table size: dial tcp xx:xx:xx:xx:3306: connect: connection refused
2023/09/08 18:06:48 slave_status.go:40: E! failed to query slave status: dial tcp xx:xx:xx:xx:3306: connect: connection refused
2023/09/08 18:06:48 metrics_reader.go:60: D! local.mysql : after gather once, duration: 56m55.887596058s
```

### System info

categraf-0.3.20 linux

### Docker

NA

### Steps to reproduce

1.正常配置配置mysql配置进行指标采集
2.大部分时间能够在1s左右完成指标采集，但偶现出现长时间挂起的现象，如上日志，一次采集耗时56分钟。

### Expected behavior

期望能够稳定的实现指标采集，如果连接失败/超时应该按照设定的时间结束，不影响后续采集

### Actual behavior

实际上可能存在长时间不超时的现象，经过跟踪代码，初步怀疑和未设置go-sql-driver/mysql中ReadTimeout有关系，还在验证中。
1、go-sql-driver/mysql/dsn.go中Config参数有3个和超时有关的定义：Timeout、ReadTimeout、WriteTimeout，分别表示连接超时时间、读超时时间以及写超时时间。
2、如果只设置了Timeout，那么在连接成功之后数据库读写出现异常，会不会可能出现长时间等待的情况？

以下是categraf inputs/mysql/mysql.go Init()代码：
ins.dsn = fmt.Sprintf("%s:%s@%s(%s)/?%s", ins.Username, ins.Password, net, ins.Address, ins.Parameters)
	conf, err := mysql.ParseDSN(ins.dsn)
	if err != nil {
		return err
	}
	if conf.Timeout == 0 {
		if ins.TimeoutSeconds == 0 {
			ins.TimeoutSeconds = 3
		}
		conf.Timeout = time.Second * time.Duration(ins.TimeoutSeconds)
	}
