### ISSUE TITLE
categraf采集input.oracle中的interval配置失效

### ISSUE THREAD

**Issue by Jerry-fmcheng** [flashcatcloud/categraf#675]
### Relevant config.toml

```toml
config.toml相关配置如下：
[global]
# global collect interval, unit: second
interval = 300

input.oracle中oracle.toml相关配置如下：
# collect interval
 interval = 15
```

### Logs from categraf

```text
2023/10/09 10:38:07 metrics_reader.go:56: D! local.oracle : before gather once
...
2023/10/09 10:53:07 metrics_reader.go:56: D! local.oracle : before gather once
```

### System info

categraf v0.3.20

### Steps to reproduce

1、配置input.oracle中的oracle.toml
2、正常启动categraf

### Expected behavior

按照input.oracle配置每隔15s采集一次

### Actual behavior

input.oracle配置未生效，仍然按照global配置进行

### Additional info

已经定位，原因是受input.oracle下metric.toml影响，如果移除掉这个文件，就能按照期望周期采集。
有两种修改方案：
1、规避方案，在metric.toml头部也增加interval配置（interval = 15）即可（这种情况无需改动代码，但建议在readme中说明，如果input下面存在多个toml文件，interval生效的是第一个文件，如果第一个文件中不存在该配置，则按照global配置执行）；
2、将metric.toml（非instance的公共配置）放到子目录中，涉及改动代码。
请评估修改方案。
