### ISSUE TITLE
input.kafka 配置多个kafka集群时，会出现cluster label覆盖的情况

### ISSUE THREAD

**Issue by xiaoziv** [flashcatcloud/categraf#68]
### Relevant config.toml

```toml
[[instances]]
labels = { cluster="clusterA" }

# log level only for kafka exporter
log_level = "error"

# Address (host:port) of Kafka server.
kafka_uris = ["clusterA:9092"]

[[instances]]
# # interval = global.interval * interval_times
# interval_times = 1

# append some labels to metrics
# cluster is a preferred tag with the cluster name. If none is provided, the first of kafka_uris will be used
labels = { cluster="clusterB" }

# log level only for kafka exporter
log_level = "error"

# Address (host:port) of Kafka server.
kafka_uris = ["clusterB:9092"]
```

### Logs from categraf

```text
xxx cluster=clusterB ...
xxx cluster=clusterB ...
xxx cluster=clusterB ...
xxx cluster=clusterB ...
```

### System info

categraf v0.1.12

### Steps to reproduce

1. 配置kafka.input
2. ./categraf --test --inputs kafka:kafka 查看输出

### Expected behavior

同时能查看clusterA clusterB的topic数据

### Actual behavior

实际只有clusterB标签的数据
