### ISSUE TITLE
采集 snmp 交换机table数据

### ISSUE THREAD

**Issue by zhuchqun** [flashcatcloud/categraf#688]
### Relevant config.toml

```toml
[[instances.table]]
oid = ".1.3.6.1.4.1.2011.5.25.31.1.1.1.1.5"
name = "cpu_usage"
inherit_tags = ["sysName","SN"]
index_as_tag = true
filters = ["A:1.3.6.1.4.1.2011.5.25.31.1.1.1.1.5:^[1-9]\\d*$"]
filters_expression = "A"

[[instances.field]]
oid = ".1.3.6.1.4.1.2011.5.25.31.1.1.1.1.7"
name = "mem_usage"
inherit_tags = ["sysName","SN"]
index_as_tag = true
filters = ["A:1.3.6.1.4.1.2011.5.25.31.1.1.1.1.7:^[1-9]\\d*$"]
filters_expression = "A"
```

### Logs from categraf

```text
2023/10/17 17:09:03 metrics_agent.go:279: E! failed to init input: local.snmp error: initializing table cpu_usage ins: getting table columns: Was that a table? SNMPv2-SMI::enterprises.2011.5.25.31.1.1.1.1.5: exit status 1
```

### System info

v0.3.32-53338592a1b6528a9429e97ca7bc0ff27466dac8, CentOS Linux release 7.9.2009 (Core)

### Steps to reproduce

1. 配置后直接拉起服务
2. ./categraf -test -inputs snmp 查看debug有报错

### Expected behavior

通过categraf采集交换机snmp table数据报错

### Actual behavior

通过categraf采集交换机snmp table数据报错
