### ISSUE TITLE
reload error

### ISSUE THREAD

**Issue by tanxiao1990** [flashcatcloud/categraf#71]
### Relevant config.toml

```toml
[global]
# whether print configs
print_configs = false

# add label(agent_hostname) to series
# "" -> auto detect hostname
# "xx" -> use specified string xx
# "$hostname" -> auto detect hostname
# "$ip" -> auto detect ip
# "$hostname-$ip" -> auto detect hostname and ip to replace the vars
hostname = ""

# will not add label(agent_hostname) if true
omit_hostname = false

# s | ms
precision = "ms"

# global collect interval
interval = 15

# [global.labels]
# region = "shanghai"
# env = "localhost"

[writer_opt]
# default: 2000
batch = 2000
# channel(as queue) size
chan_size = 10000

[[writers]]
url = "http://127.0.0.1:19000/prometheus/v1/write"

# Basic auth username
basic_auth_user = ""

# Basic auth password
basic_auth_pass = ""

# timeout settings, unit: ms
timeout = 5000
dial_timeout = 2500
max_idle_conns_per_host = 100
```

### Logs from categraf

```text
日志如下，已开启debug模式  
#!/bin/sh
nohup ./categraf -debug >> run.log 2>&1 &

2022/07/07 15:33:55 main.go:89: I! received signal: hangup
2022/07/07 15:33:55 agent.go:73: I! agent reloading
2022/07/07 15:33:55 agent.go:65: I! agent stopping
panic: send on closed channel

goroutine 1 [running]:
flashcat.cloud/categraf/agent.(*InputReader).Stop(...)
        /home/runner/work/categraf/categraf/agent/metrics_reader.go:45
flashcat.cloud/categraf/agent.(*Agent).stopMetricsAgent(...)
        /home/runner/work/categraf/categraf/agent/metrics_agent.go:90
flashcat.cloud/categraf/agent.(*Agent).Stop(0xc000cf1e38)
        /home/runner/work/categraf/categraf/agent/agent.go:67 +0xe5
flashcat.cloud/categraf/agent.(*Agent).Reload(0xc000cf1d58?)
        /home/runner/work/categraf/categraf/agent/agent.go:74 +0x57
main.handleSignal(0xc000928450?)
        /home/runner/work/categraf/categraf/main.go:94 +0x206
main.runAgent(0x0?)
        /home/runner/work/categraf/categraf/main_posix.go:12 +0x28
main.main()
        /home/runner/work/categraf/categraf/main.go:69 +0x205
```

### System info

./categraf -version v0.1.12-5357da0e95c1f0f3fb65c4c73d09af525ec40725        Linux dcnn2 2.6.32-358.el6.x86_64 #1 SMP Tue Jan 29 11:47:41 EST 2013 x86_64 x86_64 x86_64 GNU/Linux    

### Steps to reproduce

1、 kill -HUP  进程ID ，进行重载，偶尔出现以上日志（并非必现），导致categraf直接退出，严重影响监控稳定性
2、之前也提过这个issue，之前还是低版本，此问题一直存在

### Expected behavior

正常

### Actual behavior

异常退出
