### ISSUE TITLE
categraf将agent_hostname设置为IP时，将其他标签的值设置为主机名时，获取的值还是IP

### ISSUE THREAD

**Issue by wangyp910888** [flashcatcloud/categraf#715]
### Relevant config.toml

```toml
[global]
# whether print configs
print_configs = false

# add label(agent_hostname) to series
# "" -> auto detect hostname
# "xx" -> use specified string xx
# "$hostname" -> auto detect hostname
# "$ip" -> auto detect ip
# "$hostname-$ip" -> auto detect hostname and ip to replace the vars
hostname = "$ip"

# will not add label(agent_hostname) if true
omit_hostname = false

# global collect interval, unit: second
interval = 15

# input provider settings; optional: local / http
providers = ["local"]

[global.labels]
# region = "shanghai"
# env = "localhost"
hostname ="$hostname"

[log]
# file_name is the file to write logs to
file_name = "stdout"

# options below will not be work when file_name is stdout or stderr
# max_size is the maximum size in megabytes of the log file before it gets rotated. It defaults to 100 megabytes.
max_size = 100
# max_age is the maximum number of days to retain old log files based on the timestamp encoded in their filename.  
max_age = 1
# max_backups is the maximum number of old log files to retain.  
max_backups = 1
# local_time determines if the time used for formatting the timestamps in backup files is the computer's local time.  
local_time = true
# Compress determines if the rotated log files should be compressed using gzip. 
compress = false

[writer_opt]
batch = 1000
chan_size = 1000000

[[writers]]
url = "http://10.207.91.180:9090/prometheus/v1/write"

# Basic auth username
basic_auth_user = ""

# Basic auth password
basic_auth_pass = ""

## Optional headers
# headers = ["X-From", "categraf", "X-Xyz", "abc"]

# timeout settings, unit: ms
timeout = 5000
dial_timeout = 2500
max_idle_conns_per_host = 100

[http]
enable = false
address = ":9100"
print_access = false
run_mode = "release"

[ibex]
enable = false
## ibex flush interval
interval = "1000ms"
## n9e ibex server rpc address
servers = ["127.0.0.1:20090"]
## temp script dir
meta_dir = "./meta"

[heartbeat]
enable = true

# report os version cpu.util mem.util metadata
url = "http://10.207.91.190:19000/v1/n9e/heartbeat"

# interval, unit: s
interval = 10

# Basic auth username
basic_auth_user = ""

# Basic auth password
basic_auth_pass = ""

## Optional headers
# headers = ["X-From", "categraf", "X-Xyz", "abc"]

# timeout settings, unit: ms
timeout = 5000
dial_timeout = 2500
max_idle_conns_per_host = 100

[prometheus]
enable = false
scrape_config_file = "/path/to/in_cluster_scrape.yaml"
## log level, debug warn info error
log_level = "info"
## wal file storage path ,default ./data-agent
# wal_storage_path = "/path/to/storage"
## wal reserve time duration, default value is 2 hour
# wal_min_duration = 2
```

### Logs from categraf

```text
17:12:23 processes_sleeping agent_hostname=10.207.91.180 hostname=10.207.91.180 206
17:12:23 processes_total agent_hostname=10.207.91.180 hostname=10.207.91.180 207
17:12:23 processes_total_threads agent_hostname=10.207.91.180 hostname=10.207.91.180 344
17:12:23 processes_idle agent_hostname=10.207.91.180 hostname=10.207.91.180 0
17:12:23 processes_unknown agent_hostname=10.207.91.180 hostname=10.207.91.180 0
17:12:23 processes_dead agent_hostname=10.207.91.180 hostname=10.207.91.180 0
17:12:23 processes_paging agent_hostname=10.207.91.180 hostname=10.207.91.180 0
17:12:23 processes_blocked agent_hostname=10.207.91.180 hostname=10.207.91.180 0
17:12:23 processes_zombies agent_hostname=10.207.91.180 hostname=10.207.91.180 0
17:12:23 processes_stopped agent_hostname=10.207.91.180 hostname=10.207.91.180 1
17:12:23 processes_running agent_hostname=10.207.91.180 hostname=10.207.91.180 0
```

### System info

categraf 0.3.38  centos7.9 

### Steps to reproduce

1. 设置config.toml配置中hostname 
[global] 
hostname = "$ip"

2.  设置config.toml配置中[global.labels]新增hostname标签
[global.labels]
hostname = "$hostname"

3.  ./categraf  --test

### Expected behavior

输出结果中agent_hostname=10.207.91.180 和 hostname=ecs-hkjsef 两个值分别代表主机的IP地址和主机名

### Actual behavior

当global模块这么设置时
[global] 
hostname = "$ip"
输出结果中agent_hostname=10.207.91.180 和 hostname=10.207.91.180 两个值都是主机IP地址

当global模块这么设置时
[global] 
hostname = "$hostname"
输出结果中agent_hostname=ecs-hkjsef和 hostname=ecs-hkjsef 两个值都是主机名
