### ISSUE TITLE
inputs.http_response插件配置多个不同的域名，证书过期时间监控指标获取异常

### ISSUE THREAD

**Issue by nondevops** [flashcatcloud/categraf#735]
### Relevant config.toml

```toml
[prod][10.1.216.13][root@n9e conf]# cat input.http_response/http_response.toml 
## collect interval
# interval = 15

## Set the mapping of extra tags in batches
[mappings]
# "http://localhost" = { "job" = "local" }
# "https://www.baidu.com" = { "job" = "baidu" }

[[instances]]
targets = [
     "xxxx",
     "https://www.baidu.com"
]

.......
```

### Logs from categraf

```text
15:32:15 http_response_cert_expire_timestamp agent_hostname=xxx azone=bj4 cert_name=flashcat.cloud cloud=huaweiCloud machine_type=virtual method=GET region=hwhb target=https://flashcat.cloud 1722556799
15:32:15 http_response_cert_expire_timestamp agent_hostname=xxx azone=bj4 cert_name=*.sisyphe.cn cloud=huaweiCloud machine_type=virtual method=GET region=hwhb target=https://www.sisyphe.com.cn/ 1722815999
```

### System info

v6

### Steps to reproduce

无

### Expected behavior

无

### Actual behavior

![image](https://github.com/flashcatcloud/categraf/assets/12181410/875b9830-b51a-4f44-8b25-a535896ce8ff)
