### ISSUE TITLE
夜莺监控采集时间间隔五分钟时监控数据不连串

### ISSUE THREAD

**Issue by shaojiechao** [flashcatcloud/categraf#780]
### Relevant config.toml

```toml
input.exec.toml
# # collect interval
# interval = 60
[[instances]]
# # commands, support glob
commands = [
     "python /opt/scripts/test.py"
]

# # timeout for each command to complete
 timeout = 60

# # interval = global.interval * interval_times
 interval_times = 5

# # choices: influx prometheus falcon
# # influx stdout example: mesurement,labelkey1=labelval1,labelkey2=labelval2 field1=1.2,field2=2.3
 data_format = "influx"
```

### Logs from categraf

```text
无
```

### System info

ubuntu 18.04

### Steps to reproduce

config.toml全局的采集间隔时间时60秒
[global]
 interval = 60

exec.toml的间隔采集时间配置如下：
# # collect interval
# interval = 60
[[instances]]
# # commands, support glob
commands = [
     "python /opt/scripts/text.py"
]

# # interval = global.interval * interval_times
 interval_times = 5

### Expected behavior

预期监控采集点是连续的，但现在中间会间隔一些空白的值

### Actual behavior

<img width="1213" alt="image" src="https://github.com/flashcatcloud/categraf/assets/95906788/714b14ce-c76e-45b7-863a-960f49a6c05e">
