### ISSUE TITLE
ipmi插件无法使用

### ISSUE THREAD

**Issue by jack-zhuhua** [flashcatcloud/categraf#839]
### Relevant config.toml

```toml
[root@dt-packages-node input.ipmi]# cat conf.toml 
##  可选配置，categraf默认会搜索ipmitool,如果ipmitool没有安装到默认路径下，需要显示指定
# path = "/usr/bin/ipmitool"

##
## 本地采集，需要免密sudo权限
    use_sudo = true
##
## 默认是ADMINISTRATOR, 有 CALLBACK, USER, OPERATOR, ADMINISTRATOR 可选
# privilege = "ADMINISTRATOR"
##
## 如果servers 为空， 则为本地采集
##  [username[:password]@][protocol[(address)]]
servers = ["admin:admin@lan(172.22.2.56)"]

##  采集周期
interval = "30s"

## 采集超时时间
timeout = "20s"

## ipmitool 返回信息格式的版本 ，默认是1 
metric_version = 2
```

### Logs from categraf

```text
2024/03/19 16:02:50 metrics_reader.go:54: D! local.influxdb : before gather once
2024/03/19 16:02:50 metrics_agent.go:306: W! no instances for input:ipmi
```

### System info

centos7

### Steps to reproduce

1.
2.
3.
...

### Expected behavior

1

### Actual behavior

1
