### ISSUE TITLE
作为系统服务报错

### ISSUE THREAD

**Issue by zgz** [flashcatcloud/categraf#850]
### Relevant config.toml

```toml
[global]
# whether print configs
print_configs = false

# add label(agent_hostname) to series
# "" -> auto detect hostname
# "xx" -> use specified string xx
# "$hostname" -> auto detect hostname
# "$ip" -> auto detect ip
# "$hostname-$ip" -> auto detect hostname and ip to replace the vars
hostname = ""

# will not add label(agent_hostname) if true
omit_hostname = false

# global collect interval, unit: second
interval = 15

# input provider settings; optional: local / http
providers = ["local"]

# The concurrency setting controls the number of concurrent tasks spawned for each input. 
# By default, it is set to runtime.NumCPU() * 10. This setting is particularly useful when dealing
# with configurations that involve extensive instances of input like ping, net_response, or http_response.
# As multiple goroutines run simultaneously, the "ResponseTime" metric might appear larger than expected. 
# However, utilizing the concurrency setting can help mitigate this issue and optimize the response time.
concurrency = -1

# Setting http.ignore_global_labels = true if disabled report custom labels
[global.labels]
# region = "shanghai"
# env = "localhost"

[log]
# file_name is the file to write logs to
file_name = "stdout"

# options below will not be work when file_name is stdout or stderr
# max_size is the maximum size in megabytes of the log file before it gets rotated. It defaults to 100 megabytes.
max_size = 100
# max_age is the maximum number of days to retain old log files based on the timestamp encoded in their filename.  
max_age = 1
# max_backups is the maximum number of old log files to retain.  
max_backups = 1
# local_time determines if the time used for formatting the timestamps in backup files is the computer's local time.  
local_time = true
# Compress determines if the rotated log files should be compressed using gzip. 
compress = false

[writer_opt]
batch = 1000
chan_size = 1000000

[[writers]]
url = "http://192.168.10.47:17000/prometheus/v1/write"

## Optional TLS Config
# tls_min_version = "1.2"
# tls_ca = "/etc/categraf/ca.pem"
# tls_cert = "/etc/categraf/cert.pem"
# tls_key = "/etc/categraf/key.pem"
## Use TLS but skip chain & host verification
# insecure_skip_verify = true

# Basic auth username
basic_auth_user = ""

# Basic auth password
basic_auth_pass = ""

## Optional headers
# headers = ["X-From", "categraf", "X-Xyz", "abc"]

# timeout settings, unit: ms
timeout = 5000
dial_timeout = 2500
max_idle_conns_per_host = 100

[http]
enable = false
address = ":9100"
print_access = false
run_mode = "release"
ignore_hostname = false
ignore_global_labels = false

[ibex]
enable = false
## ibex flush interval
interval = "1000ms"
## n9e ibex server rpc address
servers = ["127.0.0.1:20090"]
## temp script dir
meta_dir = "./meta"

[heartbeat]
enable = true

# report os version cpu.util mem.util metadata
url = "http://192.168.10.47:17000/v1/n9e/heartbeat"

# interval, unit: s
interval = 10

# Basic auth username
basic_auth_user = ""

# Basic auth password
basic_auth_pass = ""

## Optional headers
# headers = ["X-From", "categraf", "X-Xyz", "abc"]

# timeout settings, unit: ms
timeout = 5000
dial_timeout = 2500
max_idle_conns_per_host = 100
```

### Logs from categraf

```text
● categraf.service - Opensource telemetry collector
     Loaded: loaded (/etc/systemd/system/categraf.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2024-03-25 15:47:44 CST; 2s ago
   Main PID: 1135321 (categraf)
      Tasks: 19 (limit: 629145)
     Memory: 38.4M
        CPU: 1.798s
     CGroup: /system.slice/categraf.service
             └─1135321 /opt/categraf/categraf -configs /opt/categraf/conf

3月 25 15:47:44 aeye-171 categraf[1135321]: 2024/03/25 15:47:44 metrics_agent.go:315: I! input: local.nfsclient started
3月 25 15:47:45 aeye-171 categraf[1135321]: 2024/03/25 15:47:45 metrics_agent.go:315: I! input: local.nvidia_smi started
3月 25 15:47:45 aeye-171 categraf[1135321]: 2024/03/25 15:47:45 metrics_agent.go:315: I! input: local.processes started
3月 25 15:47:45 aeye-171 categraf[1135321]: 2024/03/25 15:47:45 metrics_agent.go:315: I! input: local.self_metrics started
3月 25 15:47:45 aeye-171 categraf[1135321]: 2024/03/25 15:47:45 metrics_agent.go:315: I! input: local.sockstat started
3月 25 15:47:45 aeye-171 categraf[1135321]: 2024/03/25 15:47:45 metrics_agent.go:315: I! input: local.supervisor started
3月 25 15:47:45 aeye-171 categraf[1135321]: 2024/03/25 15:47:45 metrics_agent.go:315: I! input: local.system started
3月 25 15:47:45 aeye-171 categraf[1135321]: 2024/03/25 15:47:45 agent.go:46: I! [*agent.MetricsAgent] started
3月 25 15:47:45 aeye-171 categraf[1135321]: 2024/03/25 15:47:45 agent.go:49: I! agent started
3月 25 15:47:45 aeye-171 categraf[1135321]: 2024/03/25 15:47:45 supervisor.go:110: failed to get processes info: %w Post "http://localhost:9001/RPC2": dial tcp [::1]:9001: connect: connection refused
```

### System info

v0.3.56-0c0e292b6964999048280c5087eb1e3147874d0f

### Docker

n/a

### Steps to reproduce

1.N/A
2.2
3.3
...

### Expected behavior

N/A

### Actual behavior

N/A

### Additional info

1
