### ISSUE TITLE
0.3.57版本新增的input.supervisor导致categraf启动异常。

### ISSUE THREAD

**Issue by psk1996** [flashcatcloud/categraf#855]
### Relevant config.toml

```toml
[global]
  # whether print configs
  print_configs = false
   
   # add label(agent_hostname) to series
   # "" -> auto detect hostname
   # "xx" -> use specified string xx
   # "$hostname" -> auto detect hostname
   # "$ip" -> auto detect ip
  # "$hostname-$ip" -> auto detect hostname and ip to replace the vars
  hostname = "$hostname@$ip"
  
  # will not add label(agent_hostname) if true
  omit_hostname = false
  
  # s | ms
  precision = "ms"
  
  # global collect interval
  interval = 15
  
  [global.labels]
  #items = "js-yd-mgtv"
  
  [writer_opt]
  # default: 2000
  batch = 2000
  # channel(as queue) size
  chan_size = 10000
  
  [[writers]]
  url = ""
  
  # Basic auth username
  basic_auth_user = ""
  
  # Basic auth password
  basic_auth_pass = ""
  
  # timeout settings, unit: ms
  timeout = 5000
  dial_timeout = 2500
  max_idle_conns_per_host = 100


[http]
enable = false
address = ":9100"
print_access = false
run_mode = "release"
ignore_hostname = false
ignore_global_labels = false



input.supervisor/supervisor.toml 
# Gathers information about processes that running under supervisor using XML-RPC API
[[instances]]
## Url of supervisor's XML-RPC endpoint if basic auth enabled in supervisor http server,
## than you have to add credentials to url (ex. http://login:pass@localhost:9001/RPC2)
# url = "http://login:pass@localhost:9001/RPC2"
## With settings below you can manage gathering additional information about processes
## If both of them empty, then all additional information will be collected.
## Currently supported supported additional metrics are: pid, rc
# metrics_include = []
# metrics_exclude = ["pid", "rc"]
```

### Logs from categraf

```text
3月 27 16:55:53 DBXC-TEST categraf[1128770]: 2024/03/27 16:55:53 supervisor.go:110: failed to get processes info: %w Post "http://localhost:9001/RPC2": dial tcp 127.0.0.1:9001: connect: connection refused
3月 27 16:56:08 DBXC-TEST categraf[1128770]: 2024/03/27 16:56:08 supervisor.go:110: failed to get processes info: %w Post "http://localhost:9001/RPC2": dial tcp 127.0.0.1:9001: connect: connection refused
3月 27 16:56:23 DBXC-TEST categraf[1128770]: 2024/03/27 16:56:23 supervisor.go:110: failed to get processes info: %w Post "http://localhost:9001/RPC2": dial tcp 127.0.0.1:9001: connect: connection refused
3月 27 16:56:38 DBXC-TEST categraf[1128770]: 2024/03/27 16:56:38 supervisor.go:110: failed to get processes info: %w Post "http://localhost:9001/RPC2": dial tcp 127.0.0.1:9001: connect: connection refused
3月 27 16:56:53 DBXC-TEST categraf[1128770]: 2024/03/27 16:56:53 supervisor.go:110: failed to get processes info: %w Post "http://localhost:9001/RPC2": dial tcp 127.0.0.1:9001: connect: connection refused
3月 27 16:57:08 DBXC-TEST categraf[1128770]: 2024/03/27 16:57:08 supervisor.go:110: failed to get processes info: %w Post "http://localhost:9001/RPC2": dial tcp 127.0.0.1:9001: connect: connection refused
3月 27 16:57:23 DBXC-TEST categraf[1128770]: 2024/03/27 16:57:23 supervisor.go:110: failed to get processes info: %w Post "http://localhost:9001/RPC2": dial tcp 127.0.0.1:9001: connect: connection refused
3月 27 16:57:38 DBXC-TEST categraf[1128770]: 2024/03/27 16:57:38 supervisor.go:110: failed to get processes info: %w Post "http://localhost:9001/RPC2": dial tcp 127.0.0.1:9001: connect: connection refused
3月 27 16:57:53 DBXC-TEST categraf[1128770]: 2024/03/27 16:57:53 supervisor.go:110: failed to get processes info: %w Post "http://localhost:9001/RPC2": dial tcp 127.0.0.1:9001: connect: connection refused
3月 27 16:58:08 DBXC-TEST categraf[1128770]: 2024/03/27 16:58:08 supervisor.go:110: failed to get processes info: %w Post "http://localhost:9001/RPC2": dial tcp 127.0.0.1:9001: connect: connection refused
```

### System info

openEuler 22.03 (LTS-SP2)

### Steps to reproduce

1、从github上获取v0.3.57的包 (https://github.com/flashcatcloud/categraf/releases/download/v0.3.57/categraf-v0.3.57-linux-amd64.tar.gz)
2、在openEuler 22.03 (LTS-SP2)中部署,步骤如下：
  -- tar -xf categraf-v0.3.57-linux-amd64.tar.gz
  -- ln  -s /opt/context/categraf-v0.3.57-linux-amd64  /opt/context/categraf
  -- sudo ./categraf --install  
  -- sudo ./categraf --start 

### Expected behavior

我希望他能正常运行，并上报至服务端。

### Actual behavior

实际正常启动了。也上报了服务端。但是在通过systemctl status categraf观察时发现日志内一直在打印supervisor相关异常。 该服务器内并没有部署supervisor。 尝试注释supervisor相关input内配置文件。categraf无法启动。删除后也无法启动。

希望该插件默认不启用，而是让用户自行配置。
