### ISSUE TITLE
安装配置文件问题

### ISSUE THREAD

**Issue by yaguangtang** [flashcatcloud/categraf#856]
### Relevant config.toml

```toml
[Service]
StandardOutput=journal+console
StandardError=journal+console
StartLimitInterval=3600
StartLimitBurst=10
ExecStart=/categraf-v0.3.38-linux-amd64/categraf "-configs" "/categraf-v0.3.38-linux-amd64/conf"

WorkingDirectory=/categraf-v0.3.38-linux-amd64
```

### Logs from categraf

```text
这是多少SB的写法啊，脑袋被驴踢了嘛，写成这样的配置文件
```

### System info

categraf-v0.3.38-linux-amd64

### Steps to reproduce

1.
2.
3.
...
[Service]
StandardOutput=journal+console
StandardError=journal+console
StartLimitInterval=3600
StartLimitBurst=10
ExecStart=/categraf-v0.3.38-linux-amd64/categraf "-configs" "/categraf-v0.3.38-linux-amd64/conf"

WorkingDirectory=/categraf-v0.3.38-linux-amd64

### Expected behavior

[Service]
StandardOutput=journal+console
StandardError=journal+console
StartLimitInterval=3600
StartLimitBurst=10
ExecStart=/categraf-v0.3.38-linux-amd64/categraf "-configs" "/categraf-v0.3.38-linux-amd64/conf"

WorkingDirectory=/categraf-v0.3.38-linux-amd64

### Actual behavior

[Service]
StandardOutput=journal+console
StandardError=journal+console
StartLimitInterval=3600
StartLimitBurst=10
ExecStart=/categraf-v0.3.38-linux-amd64/categraf "-configs" "/categraf-v0.3.38-linux-amd64/conf"

WorkingDirectory=/categraf-v0.3.38-linux-amd64
