### ISSUE TITLE
categraf 使用prometheus采集ceph报错

### ISSUE THREAD

**Issue by Payton443** [flashcatcloud/categraf#867]
### Relevant config.toml

```toml
[[instances]]
urls = [
  "http://127.0.0.1:9283/metrics"
]
labels = {service="ceph",cluster="ceph-cluster"}
```

### Logs from categraf

```text
prometheus.go:236: E! failed to parse response body, url: http://127.0.0.1:9283/metrics error: E! reading text format failed: text format parsing error in line 1595: second HELP line for metric name "ceph_daemon_health_metrics"
```

### System info

OS:Rocky Linux 9.2 (Blue Onyx);ceph version 16.2.13

### Steps to reproduce

/opt/categraf/categraf --debug --inputs prometheus

### Expected behavior

报错prometheus.go:236: E! failed to parse response body, url: http://127.0.0.1:9283/metrics error: E! reading text format failed: text format parsing error in line 1595: second HELP line for metric name "ceph_daemon_health_metrics"

### Actual behavior

报错prometheus.go:236: E! failed to parse response body, url: http://127.0.0.1:9283/metrics error: E! reading text format failed: text format parsing error in line 1595: second HELP line for metric name "ceph_daemon_health_metrics"
大盘和即时查询没有ceph相关信息
