### ISSUE TITLE
null

### ISSUE THREAD

**Issue by lifehacking** [flashcatcloud/categraf#918]
### Relevant config.toml

```toml
[global]
print_configs = false
hostname = "$ip"
omit_hostname = false
interval = 15
providers = ["local"]
concurrency = -1

[global.labels]

max_size = 1000
max_age = 1
max_backups = 1
local_time = true
compress = true

[writer_opt]
batch = 2000
chan_size = 1000000

timeout = 5000
dial_timeout = 2500
max_idle_conns_per_host = 100

[http]
enable = false
address = ":9100"
print_access = false
run_mode = "release"
```

### Logs from categraf

```text


```

### System info

centos7.9 

### Steps to reproduce

...

### Expected behavior

cpu_usage_active metrics valuse
