### ISSUE TITLE
添加snmp插件添加不存在的ip采集（ping不通，或ping通采集失败），将导致整个agents目标采集失败从而无数据

### ISSUE THREAD

**Issue by robotneo** [flashcatcloud/categraf#933]
### Relevant config.toml

```toml
interval = 30

[[instances]]
agents = [
    "udp://172.16.42.1",
    "udp://172.16.42.2",
    "udp://172.16.42.3"  # 该IP是ping不通或不存在的对象
]

# metrics_name_prefix = "dell_"

interval_times = 1
labels = { region = "hangzhou", role = "idrac", brand = "dell" }

timeout = "5s"
version = 2
community = "public"
path = ["/opt/categraf/mibs/dell"]
translator = "gosmi"
agent_host_tag = "device_ip"
retries = 3
max_repetitions = 20

# iDRAC版本 racShortName
[[instances.field]]
oid = ".1.3.6.1.4.1.674.10892.5.1.1.2.0"
name = "dell_idrac_shortname"
is_tag = true

# iDRAC固件版本 racFirmwareVersion
[[instances.field]]
oid = ".1.3.6.1.4.1.674.10892.5.1.1.5.0"
name = "dell_idrac_firmware"
is_tag = true

# iDRAC界面的URL
[[instances.field]]
oid = ".1.3.6.1.4.1.674.10892.5.1.1.6.0"
name = "dell_idrac_url"
is_tag = true

# # 设备名称 iDRAC-系统服务标签
# [[instances.field]]
# oid = ".1.3.6.1.2.1.1.5.0"
# name = "system_name"
# is_tag = true

# 服务标签
[[instances.field]]
oid = ".1.3.6.1.4.1.674.10892.5.1.3.2.0"
name = "dell_service_tag"
is_tag = true

# 快速服务代码
[[instances.field]]
oid = ".1.3.6.1.4.1.674.10892.5.1.3.3.0"
name = "dell_express_service_code"
is_tag = true

# 操作系统名称
[[instances.field]]
oid = ".1.3.6.1.4.1.674.10892.5.1.3.6.0"
name = "dell_os_name"
is_tag = true

# 型号名称
[[instances.field]]
oid = ".1.3.6.1.4.1.674.10892.5.1.3.12.0"
name = "dell_model_name"
is_tag = true

# 操作系统版本
[[instances.field]]
oid = ".1.3.6.1.4.1.674.10892.5.1.3.14.0"
name = "dell_os_version"
is_tag = true

# 系统的唯一标识符或ID
[[instances.field]]
oid = ".1.3.6.1.4.1.674.10892.5.1.3.13.0"
name = "dell_system_id"

# 设备全局系统状态 globalSystemStatus
# ObjectStatusEnum (INTEGER) 
# {other(1), unknown(2), ok(3), nonCritical(4), critical(5), nonRecoverable(6) }
[[instances.field]]
oid = ".1.3.6.1.4.1.674.10892.5.2.1.0"
name = "dell_glob_system_status"

# 设备LCD状态 systemLCDStatus
# ObjectStatusEnum (INTEGER) 
# {other(1), unknown(2), ok(3), nonCritical(4), critical(5), nonRecoverable(6) }
[[instances.field]]
oid = ".1.3.6.1.4.1.674.10892.5.2.2.0"
name = "dell_system_lcd_status"

# 设备全局存储状态 globalStorageStatus
# ObjectStatusEnum (INTEGER) 
# {other(1), unknown(2), ok(3), nonCritical(4), critical(5), nonRecoverable(6) }
[[instances.field]]
oid = ".1.3.6.1.4.1.674.10892.5.2.3.0"
name = "dell_global_storage_status"

# 设备系统电源状态 systemPowerState
# PowerStateStatusEnum (INTEGER) 
# {other(1), unknown(2), off(3), on(4) }
[[instances.field]]
oid = ".1.3.6.1.4.1.674.10892.5.2.4.0"
name = "dell_system_power_state"

# 设备系统电源在线时长 systemPowerUpTime 单位秒
# Unsigned32BitRange (INTEGER) 
# (0..2147483647)
[[instances.field]]
oid = ".1.3.6.1.4.1.674.10892.5.2.5.0"
name = "dell_system_power_uptime"

# 事件日志中的条目数 numEventLogEntries
#  Unsigned32BitRange (INTEGER) 
# (0..2147483647) 
[[instances.field]]
oid = ".1.3.6.1.4.1.674.10892.5.4.300.1.0"
name = "dell_num_event_log"
```

### Logs from categraf

```text
instances.go:176: agent udp://172.16.42.3 ins: performing get on field dell_idrac_shortname(.1.3.6.1.4.1.674.10892.5.1.1.2.0): request timeout (after 3 retries)
2024/05/16 10:46:38 table.go:405: E! snmp walk error:request timeout (after 3 retries), oid:.1.3.6.1.4.1.674.10892.5.4.300.50.1.8 
2024/05/16 10:46:38 instances.go:182: agent udp://172.16.42.3 ins: gathering table dell error: performing bulk walk for field bios_version(.1.3.6.1.4.1.674.10892.5.4.300.50.1.8): request timeout (after 3 retries)
2024/05/16 10:46:58 table.go:405: E! snmp walk error:request timeout (after 3 retries), oid:.1.3.6.1.4.1.674.10892.5.4.300.60.1.4 
2024/05/16 10:46:58 instances.go:182: agent udp://172.16.42.3 ins: gathering table dell error: performing bulk walk for field firmware_state(.1.3.6.1.4.1.674.10892.5.4.300.60.1.4): request timeout (after 3 retries)
```

### System info

Ubuntu 22.04.3

### Docker

二进制和docker测试都一样

### Steps to reproduce

snmp采集插件添加不存在的IP导致整个采集失败

### Expected behavior

snmp采集插件添加不存在的IP导致整个采集失败

### Actual behavior

snmp采集插件添加不存在的IP导致整个采集失败
