### ISSUE TITLE
input.aliyun agent._hostname标签主机名有“.”的情况被忽略了，不显示"."

### ISSUE THREAD

**Issue by nondevops** [flashcatcloud/categraf#957]
### Relevant config.toml

```toml
# # collect interval
# interval = 60
[[instances]]
# # endpoint region 参考 https://help.aliyun.com/document_detail/28616.html#section-72p-xhs-6qt
region="cn-beijing"
endpoint="metrics-vpc.cn-beijing.aliyuncs.com"
access_key_id="xx"
access_key_secret="xx"
interval_times=4
delay="10m"
period="60s"

# # namespace 参考 https://help.aliyun.com/document_detail/163515.htmspm=a2c4g.11186623.0.0.44d65c58mhgNw3
namespaces=["acs_ecs_dashboard"]
[[instances.metric_filters]]
# # metric name 参考 https://help.aliyun.com/document_detail/163515.htm?spm=a2c4g.11186623.0.0.401d15c73Z0dZh
# # 参考页面中的Metric Id 填入下面的metricName ,页面中包含中文的Metric Name对应接口中的Description
metric_names=["cpu_cores","cpu_idle","cpu_system","cpu_total","cpu_user","cpu_wait","vm.TcpCount"]
namespace=""
ratelimit=25
catch_ttl="1h"
timeout="10s"
```

### Logs from categraf

```text
10:29:45 aliyun_acs_ecs_dashboard_cpu_other_minimum agent_hostname=rocketmq-server0305048183xxf ...
10:29:45 aliyun_acs_ecs_dashboard_cpu_other_average agent_hostname=es-cluster-logs-hot0305058967xxf ...
```

### System info

rocky.linux.8.5

### Steps to reproduce

修改input.aliyun相关配置
开启调试

### Expected behavior

希望将"."显示出来，input.cpu 等默认采集对象是不会忽略"."的。

### Actual behavior

input.aliyun agent._hostname标签主机名有“.”的情况被忽略了，不显示"."
