### ISSUE TITLE
使用categraf监控rockmq无法生效

### ISSUE THREAD

**Issue by a33151** [flashcatcloud/categraf#961]
### Relevant config.toml

```toml
[[inputs.rocketmq_offset]]
## The RocketMQ nameserver address
nameserver = "xx.xx.24.132:9876"

## The RocketMQ group to monitor
#group = ""

## Topics to monitor. If not specified, all topics for the group will be monitored.
#topics = [""]

## Interval to check the offsets.
#interval = "10s"

## Timeout for HTTP requests.
#timeout = "5s"
```

### Logs from categraf

```text
日志上没有任何rockmq的相关指标
```

### System info

categraf v0.3.49

### Steps to reproduce

目前怀疑的点： 由于rockmq开启的AKSK认证 但是看配置文件没有任何示例，请问是否可以补充一些 感谢

### Expected behavior

期望是能输出rockmq相关的指标

### Actual behavior

实际上没有任何MQ相关指标
