### ISSUE TITLE
使用jolokia_agent_misc监控cassandra报错

### ISSUE THREAD

**Issue by waittingsummer** [flashcatcloud/categraf#976]
### Relevant config.toml

```toml
[[instances]]
  urls = ["http://192.168.56.99:8778/jolokia"]
  metrics_name_prefix = "java_"

  [[instances.metric]]
    name  = "Memory"
    mbean = "java.lang:type=Memory"

  [[instances.metric]]
    name  = "GarbageCollector"
    mbean = "java.lang:name=*,type=GarbageCollector"
    tag_keys = ["name"]
    field_prefix = "$1_"

[[instances]]
  urls = ["http://192.168.56.99:8778/jolokia"]
  metrics_name_prefix = "cassandra_"

  [[instances.metric]]
    name  = "Cache"
    mbean = "org.apache.cassandra.metrics:name=*,scope=*,type=Cache"
    tag_keys = ["name", "scope"]
    field_prefix = "$1_"

  [[instances.metric]]
    name  = "Client"
    mbean = "org.apache.cassandra.metrics:name=*,type=Client"
    tag_keys = ["name"]
    field_prefix = "$1_"

  [[instances.metric]]
    name  = "ClientRequestMetrics"
    mbean = "org.apache.cassandra.metrics:name=*,type=ClientRequestMetrics"
    tag_keys = ["name"]
    field_prefix = "$1_"

  [[instances.metric]]
    name  = "ClientRequest"
    mbean = "org.apache.cassandra.metrics:name=*,scope=*,type=ClientRequest"
    tag_keys = ["name", "scope"]
    field_prefix = "$1_"

  [[instances.metric]]
    name  = "ColumnFamily"
    mbean = "org.apache.cassandra.metrics:keyspace=*,name=*,scope=*,type=ColumnFamily"
    tag_keys = ["keyspace", "name", "scope"]
    field_prefix = "$2_"

  [[instances.metric]]
    name  = "CommitLog"
    mbean = "org.apache.cassandra.metrics:name=*,type=CommitLog"
    tag_keys = ["name"]
    field_prefix = "$1_"

  [[instances.metric]]
    name  = "Compaction"
    mbean = "org.apache.cassandra.metrics:name=*,type=Compaction"
    tag_keys = ["name"]
    field_prefix = "$1_"

  [[instances.metric]]
    name  = "CQL"
    mbean = "org.apache.cassandra.metrics:name=*,type=CQL"
    tag_keys = ["name"]
    field_prefix = "$1_"

  [[instances.metric]]
    name  = "DroppedMessage"
    mbean = "org.apache.cassandra.metrics:name=*,scope=*,type=DroppedMessage"
    tag_keys = ["name", "scope"]
    field_prefix = "$1_"

  [[instances.metric]]
    name  = "FileCache"
    mbean = "org.apache.cassandra.metrics:name=*,type=FileCache"
    tag_keys = ["name"]
    field_prefix = "$1_"

  [[instances.metric]]
    name  = "ReadRepair"
    mbean = "org.apache.cassandra.metrics:name=*,type=ReadRepair"
    tag_keys = ["name"]
    field_prefix = "$1_"

  [[instances.metric]]
    name  = "Storage"
    mbean = "org.apache.cassandra.metrics:name=*,type=Storage"
    tag_keys = ["name"]
    field_prefix = "$1_"

  [[instances.metric]]
    name  = "ThreadPools"
    mbean = "org.apache.cassandra.metrics:name=*,path=*,scope=*,type=ThreadPools"
    tag_keys = ["name", "path", "scope"]
    field_prefix = "$1_"
```

### Logs from categraf

```text
2024/06/19 11:14:07 main.go:149: I! runner.binarydir: /opt/categraf-v0.3.69-linux-amd64
2024/06/19 11:14:07 main.go:150: I! runner.hostname: Nightingale
2024/06/19 11:14:07 main.go:151: I! runner.fd_limits: (soft=100000, hard=100000)
2024/06/19 11:14:07 main.go:152: I! runner.vm_limits: (soft=unlimited, hard=unlimited)
2024/06/19 11:14:07 provider_manager.go:60: I! use input provider: [local]
2024/06/19 11:14:07 prometheus_agent.go:19: I! prometheus scraping disabled!
2024/06/19 11:14:07 ibex_agent.go:19: I! ibex agent disabled!
2024/06/19 11:14:07 agent.go:38: I! agent starting
2024/06/19 11:14:07 metrics_agent.go:241: E! input: local.jolokia_agent_misc not supported
2024/06/19 11:14:07 agent.go:46: I! [*agent.MetricsAgent] started
2024/06/19 11:14:07 agent.go:49: I! agent started
```

### System info

categraf-v0.3.69-linux-amd64,centos8.2,cassandra 3.11.3

### Steps to reproduce

1.cassandra配置好Jolokia接口，页面访问能获取数据

![截图_选择区域_20240619110309](https://github.com/flashcatcloud/categraf/assets/32017265/7b855404-6012-49bb-a154-9c2ad583878b)

2../categraf --test --inputs jolokia_agent_misc测试报错
...

### Expected behavior

测试通过

### Actual behavior

测试报错
